# -*- coding: utf-8 -*-
"""
Whitelist der bekannten Bestandsverstöße für test_setting_integritaet.py

REGELN:
- Diese Liste darf NUR SCHRUMPFEN, niemals wachsen.
- Neue Verstöße müssen in den Setting-Daten behoben werden, nicht hier eingetragen.
- Wird ein Eintrag durch einen Datenfix obsolet, schlägt der Test fehl,
  bis der Eintrag hier entfernt wird.

KATEGORIEN der Bestandsverstöße (Stand der Generierung):
  (a) AH-Referenzen auf Arkane Hintergründe, die es nur in anderen Settings
      gibt (Talente wurden settingübergreifend kopiert), z.B. "AH (Magie)".
  (b) Freitext-Pseudo-Referenzen, die der Parser als Talent interpretiert:
      'WC' (Wild Card), Gesinnungen, Monster-Typen ('Dämon', 'Vampir', ...),
      Volk-Namen, Rang-Wörter ('Heroisch'), Handicap-Texte.
  (c) Echte Datenfehler: Deadlands-Komma-String, Tippfehler ('foder', 'Ver'),
      fehlende auto_handicaps (SciFi), auto_talent 'Zäh' (FK Oger),
      fehlende Pflichtfelder (Rippers 'Anpassungsfähig').

Generiert am 2026-06-12 aus dem Ist-Stand der settings/*.json.
"""

BEKANNTE_VERSTOESSE = {
    '50 Fathoms': {
        "Talent 'Arkane Stärkung': 'AH (Beschwörer)' muss ausgewählt sein.",
        "Talent 'Bastler': 'AH (Verrückte Wissenschaft)' muss ausgewählt sein.",
        "Talent 'Beschwörung': 'AH (Diabolist)' muss ausgewählt sein.",
        "Talent 'Böser Blick': 'AH (Hexer/Hexe)' muss ausgewählt sein.",
        "Talent 'Chemiker': 'AH (Alchemist)' muss ausgewählt sein.",
        "Talent 'Elementare Absorption': 'AH (Elementarmagier)' muss ausgewählt sein.",
        "Talent 'Elementarer Meister': 'AH (Elementarist)' muss ausgewählt sein.",
        "Talent 'Geweihter Fetisch': 'AH (Schamane)' muss ausgewählt sein.",
        "Talent 'Gnade': 'AH (Kleriker)' muss ausgewählt sein.",
        "Talent 'Grabgesang': 'AH (Barde)' muss ausgewählt sein.",
        "Talent 'Große Macht': 'AH (Zauberer)' muss ausgewählt sein.",
        "Talent 'Heiliger/Unheiliger Krieger': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Heldentum inspirieren': 'AH (Barde)' muss ausgewählt sein.",
        "Talent 'Herzholzstab': 'AH (Druide)' muss ausgewählt sein.",
        "Talent 'Hexenzeit': 'AH (Hexer/Hexe)' muss ausgewählt sein.",
        "Talent 'Höhere Beschwörung': 'AH (Beschwörer)' muss ausgewählt sein.",
        "Talent 'Infernale Rüstung': 'AH (Diabolist)' muss ausgewählt sein.",
        "Talent 'Instrument': 'AH (Barde)' muss ausgewählt sein.",
        "Talent 'Konstrukt-Vertrauter': 'AH (Tüftler)' muss ausgewählt sein.",
        "Talent 'Meisterlicher Alchemist': 'AH (Alchemist)' muss ausgewählt sein.",
        "Talent 'Meisterlicher Illusionist': 'AH (Illusionist)' muss ausgewählt sein.",
        "Talent 'Phänomenale Macht': 'AH (Zauberer)' muss ausgewählt sein.",
        "Talent 'Seelengefäß': 'AH (Nekromant)' muss ausgewählt sein.",
        "Talent 'Tödliche Illusion': 'AH (Illusionist)' muss ausgewählt sein.",
        "Talent 'Tüftlerrüstung': 'AH (Tüftler)' muss ausgewählt sein.",
        "Talent 'Ungezügelte Beschwörung': 'AH (Beschwörer)' muss ausgewählt sein.",
        "Talent 'Unheimliche Inspiration': 'AH (Magier)' muss ausgewählt sein.",
        "Talent 'Untote zerstören': 'AH (Kleriker)' muss ausgewählt sein.",
        "Talent 'Untoter Vertrauter': 'AH (Nekromant)' muss ausgewählt sein.",
        "Talent 'Urtümliche Magie': 'AH (Schamane)' muss ausgewählt sein.",
        "Talent 'Vertrauter': Einer der folgenden AH wird vorausgesetzt: Diabolist, Druide, Elementarmagier, Schamane, Hexer, Nekromant, Hexer, Zauberer",
        "Talent 'Wahre Form': 'AH (Druide)' muss ausgewählt sein.",
        "Talent 'Zauberbücher': 'AH (Magie)' muss ausgewählt sein.",
        "Talent 'Zauberer': 'AH (Magie)' muss ausgewählt sein.",
        "Talent 'Zorn der Hölle': 'AH (Diabolist)' muss ausgewählt sein.",
        "Talent 'Zusätzliche Anstrengung': 'AH (Begabt)' muss ausgewählt sein.",
    },
    'Deadlands': {
        "Talent 'AH (Verrückte Wissenschaft)': Fertigkeit 'Anfänger, VER W8+, Naturwissenschaften W6+, Verrückte Wissenschaft' nicht gefunden.",
        "Talent 'Gefolgsleute': Vorausgesetztes Talent 'WC' wurde nicht gefunden.",
        "Talent 'Handlanger': Vorausgesetztes Talent 'WC' wurde nicht gefunden.",
        "Talent 'Heiliger/Unheiliger Krieger': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
    },
    'Fantasy Kompendium': {
        "Talent 'Arkane Stärkung': Vorausgesetztes Talent 'Tier beschwören' wurde nicht gefunden.",
        "Talent 'Bastler': 'AH (Verrückte Wissenschaft)' muss ausgewählt sein.",
        "Talent 'Blutmagie': Vorausgesetztes Talent 'eine böse Gesinnung' wurde nicht gefunden.",
        "Talent 'Böe': Vorausgesetztes Talent 'Flügel' wurde nicht gefunden.",
        "Talent 'Elementare Absorption': 'AH (Elementarmagier)' muss ausgewählt sein.",
        "Talent 'Heiliger/Unheiliger Krieger': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Höhere Beschwörung': Vorausgesetztes Talent 'Monster beschwören' wurde nicht gefunden.",
        "Talent 'Höhere Beschwörung': Vorausgesetztes Talent 'Tier beschwören' wurde nicht gefunden.",
        "Talent 'Kriegsschar': Vorausgesetztes Talent 'mindestens zwei weitere Anführertalente' wurde nicht gefunden.",
        "Talent 'Mentalist': 'AH (Psionik)' muss ausgewählt sein.",
        "Talent 'Mentalist': Fertigkeit 'Psionik' nicht gefunden.",
        "Talent 'Ritter': Vorausgesetztes Talent 'Verpflichtung (schwer)' wurde nicht gefunden.",
        "Talent 'Schnelle Verwandlung': Vorausgesetztes Talent 'Lykanthropie' wurde nicht gefunden.",
        "Talent 'Ungezügelte Beschwörung': Vorausgesetztes Talent 'Monster beschwören' wurde nicht gefunden.",
        "Talent 'Versengen': Vorausgesetztes Talent 'Odemwaffe' wurde nicht gefunden.",
        "Talent 'Zauberbücher': 'AH (Magie)' muss ausgewählt sein.",
        "Talent 'Zauberer': 'AH (Magie)' muss ausgewählt sein.",
        "Volk 'Oger': auto_talent 'Zäh' existiert nicht",
    },
    'HeXXen 1773': {
        "Talent 'Bastler': 'AH (Verrückte Wissenschaft)' muss ausgewählt sein.",
        "Talent 'Heiliger/Unheiliger Krieger': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Zauberer': 'AH (Magie)' muss ausgewählt sein.",
        "Talent 'Zusätzliche Anstrengung': 'AH (Begabt)' muss ausgewählt sein.",
    },
    'Hellfrost': {
        "Talent 'Bastler': 'AH (Verrückte Wissenschaft)' muss ausgewählt sein.",
        "Talent 'Eiseskälte': 'AH (Kälte-Ausprägungen)' muss ausgewählt sein.",
        "Talent 'Elementare Absorption': 'AH (Elementarmagier)' muss ausgewählt sein.",
        "Talent 'Heiliger Krieger': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Heiliger/Unheiliger Krieger': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Dargars': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Eiras': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Eostres (Pflanzenmutter)': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Eostres (Tiermutter)': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Erthas': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Freos': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Helas': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Hoenirs': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Hothars': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Kenaz'': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Maeras': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Nauthiz'': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Neorthes': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Nihts': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Rigrs': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Scaethas': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Sigels': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Thunors': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Tiws': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Valis': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger Vars': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Jünger der Nornen': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Zauberbücher': 'AH (Magie)' muss ausgewählt sein.",
        "Talent 'Zauberer': 'AH (Magie)' muss ausgewählt sein.",
        "Talent 'Zauberfinesse': 'AH (außer Runenmagie)' muss ausgewählt sein.",
        "Talent 'Zusätzliche Anstrengung': 'AH (Begabt)' muss ausgewählt sein.",
    },
    'Horror Kompendium': {
        "Talent 'Abnehmbare Teile': Voraussetzung nicht erfüllt: {'oder': ['Flickenmonster', 'Wiedergänger']}",
        "Talent 'Alpha': Vorausgesetztes Talent 'Werwolf' wurde nicht gefunden.",
        "Talent 'Bastler': 'AH (Verrückte Wissenschaft)' muss ausgewählt sein.",
        "Talent 'Bezaubern': Vorausgesetztes Talent 'Vampir' wurde nicht gefunden.",
        "Talent 'Biss/Klauen': Vorausgesetztes Talent 'Werwolf' wurde nicht gefunden.",
        "Talent 'Dämonische Flügel': Vorausgesetztes Talent 'Dämon' wurde nicht gefunden.",
        "Talent 'Dämonische Unsterblichkeit': Vorausgesetztes Talent 'Dämon' wurde nicht gefunden.",
        "Talent 'Dämonischer Biss': Vorausgesetztes Talent 'Dämon' wurde nicht gefunden.",
        "Talent 'Engelsgleiche Zähigkeit': Vorausgesetztes Talent 'Engel' wurde nicht gefunden.",
        "Talent 'Entladen': Vorausgesetztes Talent 'Flickenmonster' wurde nicht gefunden.",
        "Talent 'Erschaffer': Vorausgesetztes Talent 'Vampir' wurde nicht gefunden.",
        "Talent 'Final Girl/Guy': Vorausgesetztes Talent ''Tugendhafte' Gesinnung' wurde nicht gefunden.",
        "Talent 'Flashbacks': Vorausgesetztes Talent 'Flickenmonster' wurde nicht gefunden.",
        "Talent 'Flügelschlag': Vorausgesetztes Talent 'Engel' wurde nicht gefunden.",
        "Talent 'Gebrüll': Voraussetzung nicht erfüllt: {'oder': ['Flickenmonster', 'Phantom', 'Werwolf']}",
        "Talent 'Gedankenfresser': Vorausgesetztes Talent 'Wiedergänger' wurde nicht gefunden.",
        "Talent 'Gestank': Vorausgesetztes Talent 'Wiedergänger' wurde nicht gefunden.",
        "Talent 'Graben': Vorausgesetztes Talent 'Mumie' wurde nicht gefunden.",
        "Talent 'Göttliche Klinge': Vorausgesetztes Talent 'Engel' wurde nicht gefunden.",
        "Talent 'Heiliger/Unheiliger Krieger': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Heiliges Licht': Vorausgesetztes Talent 'Engel' wurde nicht gefunden.",
        "Talent 'Herr der Zombies': Vorausgesetztes Talent 'Wiedergänger' wurde nicht gefunden.",
        "Talent 'Höllenfeuer (Dämon)': Vorausgesetztes Talent 'Dämon' wurde nicht gefunden.",
        "Talent 'Kinder der Nacht': Vorausgesetztes Talent 'Vampir' wurde nicht gefunden.",
        "Talent 'Klauen': Voraussetzung nicht erfüllt: {'oder': ['Dämon', 'Vampir']}",
        "Talent 'Knecht': Vorausgesetztes Talent 'Vampir' wurde nicht gefunden.",
        "Talent 'Körperlos': Vorausgesetztes Talent 'Dämon' wurde nicht gefunden.",
        "Talent 'Langsame Mumien-Regeneration': Vorausgesetztes Talent 'Mumie' wurde nicht gefunden.",
        "Talent 'Mentalist': 'AH (Psionik)' muss ausgewählt sein.",
        "Talent 'Mumienfäule': Vorausgesetztes Talent 'Mumie' wurde nicht gefunden.",
        "Talent 'Nebelform': Vorausgesetztes Talent 'Vampir' wurde nicht gefunden.",
        "Talent 'Panzerhaut': Vorausgesetztes Talent 'Dämon' wurde nicht gefunden.",
        "Talent 'Phantom-Unsichtbarkeit': Vorausgesetztes Talent 'Phantom' wurde nicht gefunden.",
        "Talent 'Regeneration (schnell)': Voraussetzung nicht erfüllt: {'oder': ['Vampir', 'Werwolf']}",
        "Talent 'Schaurige Berührung': Vorausgesetztes Talent 'Phantom' wurde nicht gefunden.",
        "Talent 'Schneller Flug': Vorausgesetztes Talent 'Engel' wurde nicht gefunden.",
        "Talent 'Schwarmrufer': Vorausgesetztes Talent 'Mumie' wurde nicht gefunden.",
        "Talent 'Sprachen sprechen': Vorausgesetztes Talent 'Engel' wurde nicht gefunden.",
        "Talent 'Sprechen': Vorausgesetztes Talent 'Werwolf' wurde nicht gefunden.",
        "Talent 'Sturmrufer': Vorausgesetztes Talent 'Mumie' wurde nicht gefunden.",
        "Talent 'Tagschreiter': Vorausgesetztes Talent 'Vampir' wurde nicht gefunden.",
        "Talent 'Tiergestalt': Vorausgesetztes Talent 'Vampir' wurde nicht gefunden.",
        "Talent 'Todesberührung': Vorausgesetztes Talent 'Wiedergänger' wurde nicht gefunden.",
        "Talent 'Unerbittlicher Verfolger': Vorausgesetztes Talent 'Wiedergänger' wurde nicht gefunden.",
        "Talent 'Unsterblichkeit der Engel': Vorausgesetztes Talent 'Engel' wurde nicht gefunden.",
        "Talent 'Wahrer Dämon': Vorausgesetztes Talent 'Dämon' wurde nicht gefunden.",
        "Talent 'Wandkrabbler': Voraussetzung nicht erfüllt: {'oder': ['Vampir', 'Werwolf']}",
        "Talent 'Zauberer': 'AH (Magie)' muss ausgewählt sein.",
        "Talent 'Zusätzliche Anstrengung': 'AH (Begabt)' muss ausgewählt sein.",
        "Talent 'Zähigkeit': Vorausgesetztes Talent 'Werwolf' wurde nicht gefunden.",
        "Talent 'Überfressen': Vorausgesetztes Talent 'Vampir' wurde nicht gefunden.",
        "Talent 'Übergang': Vorausgesetztes Talent 'Phantom' wurde nicht gefunden.",
        "Talent 'Übernatürliches Spüren': Voraussetzung nicht erfüllt: {'oder': ['Dämon', 'Engel']}",
    },
    'Rippers': {
        "Talent 'Anpassungsfähig': Feld 'kategorie' fehlt",
        "Talent 'Anpassungsfähig': Feld 'voraussetzungen' fehlt",
        "Talent 'Heiliger/Unheiliger Krieger': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Zusätzliche Anstrengung': 'AH (Begabt)' muss ausgewählt sein.",
    },
    'SWAE': {
        "Talent 'Heiliger/Unheiliger Krieger': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
    },
    'Savage Aventurien': {
        "Talent 'AH (Fey)': Eine der folgenden Voraussetzungen muss erfüllt sein: Elf oder Halbelf",
        "Talent 'Blutmagie': Vorausgesetztes Talent 'eine böse Gesinnung' wurde nicht gefunden.",
        "Talent 'Elfenlieder': Eine der folgenden Voraussetzungen muss erfüllt sein: Elf oder Halbelf",
        "Talent 'Flinker Angreifer': Volk-Eigenschaft: sprinter (keine Volk-Eigenschaft)",
        "Talent 'Gefolgsleute': Vorausgesetztes Talent 'WC' wurde nicht gefunden.",
        "Talent 'Gjalsker Tierkrieger': Vorausgesetztes Talent 'Kultur: Gjalsker' wurde nicht gefunden.",
        "Talent 'Handlanger': Vorausgesetztes Talent 'WC' wurde nicht gefunden.",
        "Talent 'Hinterhalt-Gespür': Fertigkeit 'Aufmerksamkeit' nicht gefunden.",
        "Talent 'Kriegsschar': Vorausgesetztes Talent 'mindestens zwei weitere Anführertalente' wurde nicht gefunden.",
        "Talent 'Meisterspion': Fertigkeit 'Aufmerksamkeit' nicht gefunden.",
        "Talent 'Meisterspion': Fertigkeit 'Auftreten' nicht gefunden.",
        "Talent 'Ritter': Vorausgesetztes Talent 'Verpflichtung (schwer)' wurde nicht gefunden.",
        "Talent 'Tiefblick': Voraussetzung nicht erfüllt: {'oder': ['Volk-Eigenschaft: dunkelsicht', 'Volk-Eigenschaft: nachtsicht']}",
        "Talent 'Unbeugsamer Verteidiger': Eine der folgenden Voraussetzungen muss erfüllt sein: Keine Rüstungsbeschränkung oder Behindernde Rüstung",
        "Talent 'Zertrümmern': Vorausgesetztes Talent 'Halb-Ork' wurde nicht gefunden.",
        "Talent 'Zusätzliche Anstrengung': Fertigkeit 'Fokus' nicht gefunden.",
    },
    'Savage Pathfinder': {
        "Talent 'Arkane Meisterschaft (Hexe)': Vorausgesetztes Talent 'Hexe' wurde nicht gefunden.",
        "Talent 'Arkane Meisterschaft (Hexenmeister)': Vorausgesetztes Talent 'Hexenmeister' wurde nicht gefunden.",
        "Talent 'Arkane Meisterschaft (Magier)': Vorausgesetztes Talent 'Magier' wurde nicht gefunden.",
        "Talent 'Arkane Meisterschaft (Zauberer)': Vorausgesetztes Talent 'Zauberer' wurde nicht gefunden.",
        "Talent 'Bannlied': Vorausgesetztes Talent 'Barde' wurde nicht gefunden.",
        "Talent 'Bevorzugte Mächte (Druide)': Vorausgesetztes Talent 'Druide' wurde nicht gefunden.",
        "Talent 'Bevorzugte Mächte (Kleriker)': Vorausgesetztes Talent 'Kleriker' wurde nicht gefunden.",
        "Talent 'Bevorzugte Mächte (Magier)': Vorausgesetztes Talent 'Magier' wurde nicht gefunden.",
        "Talent 'Bevorzugte Mächte (Zauberer)': Vorausgesetztes Talent 'Zauberer' wurde nicht gefunden.",
        "Talent 'Böser Blick': 'AH (Hexer/Hexe)' muss ausgewählt sein.",
        "Talent 'Elementare Absorption': 'AH (Elementarmagier)' muss ausgewählt sein.",
        "Talent 'Elementare Reise': Eine der folgenden Voraussetzungen muss erfüllt sein: Ifrits oder Oreads oder Sylphen oder Undinen",
        "Talent 'Flügel der Luft': Vorausgesetztes Talent 'Sylphen' wurde nicht gefunden.",
        "Talent 'Gefolgsleute': Vorausgesetztes Talent 'WC' wurde nicht gefunden.",
        "Talent 'Grandioser Hex': Vorausgesetztes Talent 'Hexe' wurde nicht gefunden.",
        "Talent 'Große Offenbarung': Vorausgesetztes Talent 'Orakel' wurde nicht gefunden.",
        "Talent 'Großer Hex': Vorausgesetztes Talent 'Hexe' wurde nicht gefunden.",
        "Talent 'Göttliche Meisterschaft (Druide)': Vorausgesetztes Talent 'Druide' wurde nicht gefunden.",
        "Talent 'Göttliche Meisterschaft (Kleriker)': Vorausgesetztes Talent 'Kleriker' wurde nicht gefunden.",
        "Talent 'Göttliche Meisterschaft': Vorausgesetztes Talent 'Orakel' wurde nicht gefunden.",
        "Talent 'Handlanger': Vorausgesetztes Talent 'WC' wurde nicht gefunden.",
        "Talent 'Heiliger/Unheiliger Krieger': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Hexenzeit': 'AH (Hexer/Hexe)' muss ausgewählt sein.",
        "Talent 'Hinterhalt-Gespür': Fertigkeit 'Aufmerksamkeit' nicht gefunden.",
        "Talent 'Innerer Atem': Vorausgesetztes Talent 'Sylphen' wurde nicht gefunden.",
        "Talent 'Klagelied': Vorausgesetztes Talent 'Barde' wurde nicht gefunden.",
        "Talent 'Kletterranke': Vorausgesetztes Talent 'Weinranken-Leshy' wurde nicht gefunden.",
        "Talent 'Kudzu-Ringer': Vorausgesetztes Talent 'Weinranken-Leshy' wurde nicht gefunden.",
        "Talent 'Meisteralchemist': Vorausgesetztes Talent 'Mutagene' wurde nicht gefunden.",
        "Talent 'Meisterspion': Fertigkeit 'Aufmerksamkeit' nicht gefunden.",
        "Talent 'Meisterspion': Fertigkeit 'Auftreten' nicht gefunden.",
        "Talent 'Mystische Kräfte': Vorausgesetztes Talent 'Fortgeschritten' wurde nicht gefunden.",
        "Talent 'Mächtige Blutlinie': Vorausgesetztes Talent 'Zauberer' wurde nicht gefunden.",
        "Talent 'Mächtige Hexerei': Vorausgesetztes Talent 'Hexenmeister' wurde nicht gefunden.",
        "Talent 'Offenbarung': Vorausgesetztes Talent 'Orakel' wurde nicht gefunden.",
        "Talent 'Oread-Gräber': Vorausgesetztes Talent 'Oreads' wurde nicht gefunden.",
        "Talent 'Starke Hexerei': Vorausgesetztes Talent 'Hexenmeister' wurde nicht gefunden.",
        "Talent 'Tiefblick': Voraussetzung nicht erfüllt: {'oder': ['Volk-Eigenschaft: dunkelsicht', 'Volk-Eigenschaft: nachtsicht']}",
        "Talent 'Tiergestalt': Vorausgesetztes Talent 'Druide' wurde nicht gefunden.",
        "Talent 'Unbeugsamer Verteidiger': Eine der folgenden Voraussetzungen muss erfüllt sein: Keine Rüstungsbeschränkung oder Behindernde Rüstung",
        "Talent 'Unbeugsamer Verteidiger': Vorausgesetztes Talent 'Nerven aus Stahl' wurde nicht gefunden.",
        "Talent 'Versengende Waffe': Vorausgesetztes Talent 'Ifrits' wurde nicht gefunden.",
        "Talent 'Wasserabstammung': Vorausgesetztes Talent 'Undinen' wurde nicht gefunden.",
        "Talent 'Weitere Hexerei': Vorausgesetztes Talent 'Hexenmeister' wurde nicht gefunden.",
        "Talent 'Wissenshüter': Fertigkeit 'Ver' nicht gefunden.",
        "Talent 'Zauberbücher': 'AH (Magie)' muss ausgewählt sein.",
        "Talent 'Zertrümmern': Vorausgesetztes Talent 'Halb-Ork' wurde nicht gefunden.",
        "Talent 'Zornprophet': 'AH (Wunder oder Orakel)' muss ausgewählt sein.",
        "Talent 'Zusätzliche Anstrengung': 'AH (Begabt)' muss ausgewählt sein.",
        "Talent 'Zusätzlicher Hex': Vorausgesetztes Talent 'Hexe' wurde nicht gefunden.",
    },
    'SciFi Kompendium': {
        "Talent 'Bastler': 'AH (Verrückte Wissenschaft)' muss ausgewählt sein.",
        "Talent 'Heiliger/Unheiliger Krieger': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Mentalist': 'AH (Psionik)' muss ausgewählt sein.",
        "Talent 'Zauberer': 'AH (Magie)' muss ausgewählt sein.",
        "Talent 'Zusätzliche Anstrengung': 'AH (Begabt)' muss ausgewählt sein.",
        "Volk 'Insektoide': auto_handicap 'Außenseiter (leicht)' existiert nicht",
        "Volk 'Racker': auto_handicap 'Volksfeind (Insektoide)' existiert nicht",
        "Volk 'Synthetische Wesen': auto_handicap 'Programmiert (schwer)' existiert nicht",
        "Volk 'Vierarmige': auto_handicap 'Volksfeind (SL-Wahl)' existiert nicht",
        "Volk 'Wechselbälger': auto_handicap 'Außenseiter (leicht)' existiert nicht",
    },
    'Sundered Skies': {
        "Talent 'Bastler': 'AH (Verrückte Wissenschaft)' muss ausgewählt sein.",
        "Talent 'Befleckter': 'AH (Magie)' muss ausgewählt sein.",
        "Talent 'Blattsegen': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Böser Blick': 'AH (Hexe)' muss ausgewählt sein.",
        "Talent 'Düsterer Troubadour': Vorausgesetztes Talent 'AH Priester' wurde nicht gefunden.",
        "Talent 'Eisenzehnt': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Elementare Absorption': 'AH (Elementarmagier)' muss ausgewählt sein.",
        "Talent 'Friedensstifter': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Gefolgsleute': Vorausgesetztes Talent 'WC' wurde nicht gefunden.",
        "Talent 'Geliebte(r)': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Glühmagus': 'AH (Leerewandler)' muss ausgewählt sein.",
        "Talent 'Gottesgeschenk': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Handlanger': Vorausgesetztes Talent 'WC' wurde nicht gefunden.",
        "Talent 'Heiliger/Unheiliger Krieger': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Hexenzeit': 'AH (Hexe)' muss ausgewählt sein.",
        "Talent 'Kuss der Lebensmutter': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Sangespriester': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Seelenopfer': Eine der folgenden Voraussetzungen muss erfüllt sein: Wissen (Übernatürliches) oder Glaube",
        "Talent 'Ungezähmter': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Vierfachschuss': Fertigkeit 'Athletik W10+ foder Schießen' nicht gefunden.",
        "Talent 'Vierfachschuss': Vorausgesetztes Talent 'Heroisch' wurde nicht gefunden.",
        "Talent 'Vom Wind gesegnet': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Waffenbann': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Windsucher': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Zauberbücher': 'AH (Magie)' muss ausgewählt sein.",
        "Talent 'Zauberer': 'AH (Magie)' muss ausgewählt sein.",
        "Talent 'Zusätzliche Anstrengung': 'AH (Begabt)' muss ausgewählt sein.",
    },
    'Superkräfte Kompendium': {
        "Talent 'Bastler': 'AH (Verrückte Wissenschaft)' muss ausgewählt sein.",
        "Talent 'Heiliger/Unheiliger Krieger': Ein Arkaner Hintergrund 'AH (Wunder: Gott)' wird vorausgesetzt (Geweihter).",
        "Talent 'Mentalist': 'AH (Psionik)' muss ausgewählt sein.",
        "Talent 'Zauberer': 'AH (Magie)' muss ausgewählt sein.",
        "Talent 'Zusätzliche Anstrengung': 'AH (Begabt)' muss ausgewählt sein.",
    },
}
