# Define the values and constants here

settingregeln = {
    'Dynamischer Rückschlag': False,
    'Entschlossenheit': False,
    'Fanatiker': False,
    'Fertigkeitsspezialisierungen': False,
    'Fieser Schaden': False,
    'Geborener Held': False,
    'Große Abenteuer': False,
    'Helden sterben nie': False,
    'Keine Machtpunkte': False,
    'Kreativer Kampf': False,
    'Mehr Fertigkeitspunkte': False,
    'Mehr Sprachen': False,
    'Narrenglück': False,
    'Schnelle Genesung': False,
    'Schwere Entscheidungen': False,
    'Ungepanzerter Held': False,
    'Wundobergrenze': False
}
voelker = {
    'Android': {
        'Handicaps': ['Außenseiter (Schwer)', 'Pazifist (Schwer)', 'Schwur (Schwer)'],
        'Talente': ['Konstrukt'],
        'Besonderheiten': ['Künstliche Intelligenz', 'Individuelle Persönlichkeit']
    },
    'Aquarianer': {
        'Handicaps': ['Abhängigkeit'],
        'Talente': [],
        'Besonderheiten': ['Nachtsicht', 'Robustheit', 'Wasserwesen']
    },
    'Avion': {
        'Handicaps': ['Nichtschwimmer', 'Verringerte Bewegungsweite'],
        'Talente': ['Scharfe Sinne'],
        'Besonderheiten': ['Fliegen', 'Verringerte Bewegungsweite']
    },
    'Halbelfe': {
        'Handicaps': ['Außenseiter (Leicht)'],
        'Talente': [],
        'Besonderheiten': ['Erbe', 'Nachtsicht']
    },
    'Elf': {
        'Handicaps': ['Zwei linke Hände'],
        'Talente': [],
        'Besonderheiten': ['Geschickt', 'Nachtsicht']
    },
    'Halbling': {
        'Handicaps': [],
        'Talente': ['Glück'],
        'Besonderheiten': ['Beherzt', 'Größe -1', 'Verringerte Bewegungsweite']
    },
    'Mensch': {
        'Handicaps': [],
        'Talente': ['Anpassungsfähig'],
        'Besonderheiten': ['Anpassungsfähig']
    },
    'Rakashaner': {
        'Handicaps': ['Blutrünstig', 'Nichtschwimmer', 'Volksfeind'],
        'Talente': [],
        'Besonderheiten': ['Geschickt', 'Nachtsicht', 'Zähne und Krallen']
    },
    'Saurianer': {
        'Handicaps': ['Außenseiter (Leicht)', 'Kälteempfindlichkeit'],
        'Talente': ['Biss'],
        'Besonderheiten': ['Biss', 'Panzierung +2', 'Scharfe Sinne']
    },
    'Zwerg': {
        'Handicaps': ['Verringerte Bewegungsweite'],
        'Talente': [],
        'Besonderheiten': ['Nachtsicht', 'Verringerte Bewegungsweite', 'Widerstandsfähig']
    }
}
konzept = {
            'Name': ' ',
            'Name (Spieler)': ' ',
            'Volk': ' ',
            'Geschlecht': ' ',
            'Alter': ' ',
            'Profession': ' ',
            'Konzept': ' ',
            'Sprachen': ' '
        }
details = {          
            'Beschreibung': ' ',
            'Hintergrund': ' '
        }
fertigkeiten = {
            'Athletik* ': {'Geschicklichkeit'}, 
            'Heimlichkeit* ': {'Geschicklichkeit'}, 
            'Kämpfen': {'Geschicklichkeit'},
            'Schießen': {'Geschicklichkeit'}, 
            'Diebeskunst': {'Geschicklichkeit'},      
            'Überleben': {'Geschicklichkeit'},
            'Reiten': {'Geschicklichkeit'}, 
            'Fahren': {'Geschicklichkeit'}, 
            'Seefahrt': {'Geschicklichkeit'}, 
            'Pilot': {'Geschicklichkeit'}, 
            'Überreden* ': {'Willenskraft'},
            'Darbietung': {'Willenskraft'},
            'Einschüchtern': {'Willenskraft'},
            'Fokus': {'Willenskraft'}, 
            'Glaube': {'Willenskraft'},        
            'Allgemeinwissen* ': {'Verstand'}, 
            'Wahrnehmung* ': {'Verstand'}, 
            'Heilen': {'Verstand'},
            'Provozieren': {'Verstand'},             
            'Recherche': {'Verstand'}, 
            'Reparieren': {'Verstand'}, 
            'Überleben': {'Verstand'},
            'Glücksspiel': {'Verstand'},
            'Kriegskunst': {'Verstand'},
            'Okkultismus': {'Verstand'},
            'Geisteswissenschaften': {'Verstand'},
            'Naturwissenschaften': {'Verstand'},             
            'Sprache': {'Verstand'},               
            'Elektronik': {'Verstand'}, 
            'Hacken': {'Verstand'}, 
            'Zaubern': {'Verstand'}, 
            'Psionik': {'Verstand'},
            'Verrückte Wissenschaft': {'Verstand'},             
        }

maechte = {
    'Abwehren': {'Rang': 'A', 'Machtpunkte': 3, 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Arkaner Schutz': {'Rang': 'A', 'Machtpunkte': 1, 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Arkanes entdecken/verbergen': {'Rang': 'A', 'Machtpunkte': 2, 'Reichweite': 'VER S', 'Dauer': '—'},
    'Aufheben': {'Rang': 'F', 'Machtpunkte': 1, 'Reichweite': 'VER', 'Dauer': 'Sofort'},
    'Barriere': {'Rang': 'F', 'Machtpunkte': 2, 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Betäuben': {'Rang': 'F', 'Machtpunkte': 2, 'Reichweite': 'VER', 'Dauer': 'Sofort'},
    'Blenden': {'Rang': 'A', 'Machtpunkte': 2, 'Reichweite': 'VER', 'Dauer': 'Sofort'},
    'Dunkelsicht': {'Rang': 'A', 'Machtpunkte': 1, 'Reichweite': 'VER', 'Dauer': '1 Stunde'},
    'Eigenschaft erhöhen/senken': {'Rang': 'A', 'Machtpunkte': 2, 'Reichweite': 'VER 5', 'Dauer': 'Sofort/5'},
    'Elementarmanipulation': {'Rang': 'A', 'Machtpunkte': 1, 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Empathie': {'Rang': 'A', 'Machtpunkte': 1, 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Fernsicht': {'Rang': 'F', 'Machtpunkte': 2, 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Flächenschlag': {'Rang': 'F', 'Machtpunkte': 3, 'Reichweite': 'VER×2', 'Dauer': 'Sofort'},
    'Fliegen': {'Rang': 'V', 'Machtpunkte': 3, 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Furcht': {'Rang': 'A', 'Machtpunkte': 2, 'Reichweite': 'VER', 'Dauer': 'Sofort'},
    'Gedankenleere': {'Rang': 'V', 'Machtpunkte': 3, 'Reichweite': 'VER', 'Dauer': 'Sofort'},
    'Gedankenlesen': {'Rang': 'A', 'Machtpunkte': 2, 'Reichweite': 'VER', 'Dauer': 'Sofort'},
    'Gedankenverbindung': {'Rang': 'A', 'Machtpunkte': 1, 'Reichweite': 'VER 30m', 'Dauer': '—'},
    'Geräusch/Stille': {'Rang': 'A', 'Machtpunkte': 1, 'Reichweite': 'VERx5/VER', 'Dauer': '5/Sofort'},
    'Geschoss': {'Rang': 'A', 'Machtpunkte': 1, 'Reichweite': 'VER×2', 'Dauer': 'Sofort'},
    'Gestaltwandeln': {'Rang': 'A', 'Machtpunkte': 'Speziell', 'Reichweite': 'Selbst', 'Dauer': '5'},
    'Graben': {'Rang': 'A', 'Machtpunkte': 2, 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Heilung': {'Rang': 'A', 'Machtpunkte': 3, 'Reichweite': 'B', 'Dauer': 'Sofort'},
    'Illusion': {'Rang': 'A', 'Machtpunkte': 3, 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Kriegersegen': {'Rang': 'F', 'Machtpunkte': 4, 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Licht/Dunkelheit': {'Rang': 'A', 'Machtpunkte': 2, 'Reichweite': 'VER 10m', 'Dauer': '—'},
    'Linderung': {'Rang': 'A', 'Machtpunkte': 1, 'Reichweite': 'VER', 'Dauer': 'Sofort'},
    'Marionette': {'Rang': 'V', 'Machtpunkte': 3, 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Objekt auslesen': {'Rang': 'F', 'Machtpunkte': 2, 'Reichweite': 'B', 'Dauer': 'S'},
    'Schadensfeld': {'Rang': 'F', 'Machtpunkte': 4, 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Schlummer': {'Rang': 'F', 'Machtpunkte': 2, 'Reichweite': 'VER', 'Dauer': '1 Stunde'},
    'Schutz': {'Rang': 'A', 'Machtpunkte': 1, 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Schutz vor Naturgewalten': {'Rang': 'A', 'Machtpunkte': 2, 'Reichweite': 'VER', 'Dauer': '1 Stunde'},
    'Sprachen sprechen': {'Rang': 'A', 'Machtpunkte': 1, 'Reichweite': 'VER 10m', 'Dauer': '—'},
    'Strahl': {'Rang': 'A', 'Machtpunkte': 2, 'Reichweite': 'Kegel', 'Dauer': 'Sofort'},
    'Telekinese': {'Rang': 'F', 'Machtpunkte': 5, 'Reichweite': 'VER×2', 'Dauer': '5'},
    'Teleportation': {'Rang': 'F', 'Machtpunkte': 2, 'Reichweite': 'VER', 'Dauer': 'Sofort'},
    'Tierfreund': {'Rang': 'A', 'Machtpunkte': 'Speziell', 'Reichweite': 'VER 10m', 'Dauer': '—'},
    'Trägheit/Beschleunigung': {'Rang': 'F', 'Machtpunkte': 2, 'Reichweite': 'VER', 'Dauer': 'Sofort/5'},
    'Unberührbarkeit': {'Rang': 'H', 'Machtpunkte': 5, 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Unsichtbarkeit': {'Rang': 'F', 'Machtpunkte': 5, 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Verbannen': {'Rang': 'V', 'Machtpunkte': 3, 'Reichweite': 'VER', 'Dauer': 'Sofort'},
    'Verbündeten beschwören': {'Rang': 'A', 'Machtpunkte': 'Speziell', 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Verkleiden': {'Rang': 'F', 'Machtpunkte': 2, 'Reichweite': 'VER 10m', 'Dauer': '—'},
    'Verstricken': {'Rang': 'A', 'Machtpunkte': 2, 'Reichweite': 'VER', 'Dauer': 'Sofort'},
    'Verwirrung': {'Rang': 'A', 'Machtpunkte': 1, 'Reichweite': 'VER', 'Dauer': 'S'},
    'Wachsen/Schrumpfen': {'Rang': 'F', 'Machtpunkte': 'S', 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Waffe verbessern': {'Rang': 'A', 'Machtpunkte': 2, 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Wandkrabbler': {'Rang': 'A', 'Machtpunkte': 2, 'Reichweite': 'VER 5', 'Dauer': '—'},
    'Wiederauferstehung': {'Rang': 'H', 'Machtpunkte': 30, 'Reichweite': 'B', 'Dauer': 'Sofort'},
    'Zombie': {'Rang': 'V', 'Machtpunkte': 3, 'Reichweite': 'VER', 'Dauer': '1 Stunde'},
    'Zwiesprache': {'Rang': 'H', 'Machtpunkte': 5, 'Reichweite': 'Selbst', 'Dauer': '5m'}
}
hintergrund_talente = {
    'Aristokrat': {'Rang': 'A', 'Voraussetzungen': []},
    'Arkane Resistenz': {'Rang': 'A', 'Voraussetzungen': ['WIL W8']},
    'Starke Arkane Resistenz': {'Rang': 'A', 'Voraussetzungen': ['Arkane Resistenz']},
    'Arkaner Hintergrund': {'Rang': 'A', 'Voraussetzungen': []},
    'Attraktiv': {'Rang': 'A', 'Voraussetzungen': ['KON W6']},
    'Sehr Attraktiv': {'Rang': 'A', 'Voraussetzungen': ['Attraktiv']},
    'Aufmerksamkeit': {'Rang': 'A', 'Voraussetzungen': []},
    'Beidhändig': {'Rang': 'A', 'Voraussetzungen': ['GES W8']},
    'Bekannt': {'Rang': 'A', 'Voraussetzungen': []},
    'Berühmt': {'Rang': 'F', 'Voraussetzungen': ['Bekannt']},
    'Berserker': {'Rang': 'A', 'Voraussetzungen': []},
    'Charismatisch': {'Rang': 'A', 'Voraussetzungen': ['WIL W8']},
    'Elan': {'Rang': 'A', 'Voraussetzungen': ['WIL W8']},
    'Flink': {'Rang': 'A', 'Voraussetzungen': ['GES W6']},
    'Glück': {'Rang': 'A', 'Voraussetzungen': []},
    'Großes Glück': {'Rang': 'A', 'Voraussetzungen': ['Glück']},
    'Kräftig': {'Rang': 'A', 'Voraussetzungen': ['STÄ W6', 'KON W6']},
    'Linguist': {'Rang': 'A', 'Voraussetzungen': ['VER W6']},
    'Mutig': {'Rang': 'A', 'Voraussetzungen': ['WIL W6']},
    'Reich': {'Rang': 'A', 'Voraussetzungen': []},
    'Stinkreich': {'Rang': 'A', 'Voraussetzungen': ['Reich']},
    'Rohling': {'Rang': 'A', 'Voraussetzungen': ['STÄ W6', 'KON W6']},
    'Schnell': {'Rang': 'A', 'Voraussetzungen': ['GES W8']},
    'Schnelle Heilung': {'Rang': 'A', 'Voraussetzungen': ['KON W8']}
}
kampf_talente = {
    'Ausweichen': {'Rang': 'F', 'Voraussetzungen': ['GES W8']},
    'Schnelles Ausweichen': {'Rang': 'F', 'Voraussetzungen': ['Ausweichen']},
    'Beidhändiger Fernkampf': {'Rang': 'A', 'Voraussetzungen': ['GES W8']},
    'Beidhändiger Kampf': {'Rang': 'A', 'Voraussetzungen': ['GES W8']},
    'Berechnend': {'Rang': 'A', 'Voraussetzungen': ['VER W8']},
    'Block': {'Rang': 'F', 'Voraussetzungen': ['Kämpfen W8']},
    'Harter Block': {'Rang': 'V', 'Voraussetzungen': ['Block']},
    'Doppelschuss': {'Rang': 'F', 'Voraussetzungen': ['Schießen W6']},
    'Eisenkiefer': {'Rang': 'A', 'Voraussetzungen': ['KON W8']},
    'Erstschlag': {'Rang': 'A', 'Voraussetzungen': ['GES W8']},
    'Schneller Erstschlag': {'Rang': 'H', 'Voraussetzungen': ['Erstschlag']},
    'Finte': {'Rang': 'A', 'Voraussetzungen': ['Kämpfen W8']},
    'Improvisationsgabe': {'Rang': 'F', 'Voraussetzungen': ['VER W6']},
    'Kampfkünstler': {'Rang': 'A', 'Voraussetzungen': ['Kämpfen W6']},
    'Kampfkunstmeister': {'Rang': 'F', 'Voraussetzungen': ['Kampfkünstler']},
    'Kampfreflexe': {'Rang': 'F', 'Voraussetzungen': []},
    'Keine Gnade': {'Rang': 'F', 'Voraussetzungen': []},
    'Killerinstinkt': {'Rang': 'F', 'Voraussetzungen': []},
    'Kühler Kopf': {'Rang': 'F', 'Voraussetzungen': ['VER W8']},
    'Sehr Kühler Kopf': {'Rang': 'F', 'Voraussetzungen': ['Kühler Kopf']},
    'Lieblingswaffe': {'Rang': 'A', 'Voraussetzungen': ['W8 in relevanter Fertigkeit']},
    'Absolute Lieblingswaffe': {'Rang': 'F', 'Voraussetzungen': ['Lieblingswaffe']},
    'Mächtiger Hieb': {'Rang': 'WC', 'Voraussetzungen': ['A', 'Kämpfen W8']},
    'Meisterschütze': {'Rang': 'F', 'Voraussetzungen': ['Athletik oder Schießen W8']},
    'Parkour': {'Rang': 'A', 'Voraussetzungen': ['GES W8']},
    'Raufbold': {'Rang': 'A', 'Voraussetzungen': ['STÄ W8', 'KON W8']},
    'Schläger': {'Rang': 'F', 'Voraussetzungen': ['Raufbold']},
    'Riesentöter': {'Rang': 'V', 'Voraussetzungen': []},
    'Riposte': {'Rang': 'F', 'Voraussetzungen': ['Kämpfen W8']},
    'Geschickte Riposte': {'Rang': 'V', 'Voraussetzungen': ['Riposte']},
    'Rückzug': {'Rang': 'A', 'Voraussetzungen': ['GES W8']},
    'Wendiger Rückzug': {'Rang': 'F', 'Voraussetzungen': ['Rückzug']},
    'Ruhige Hände': {'Rang': 'A', 'Voraussetzungen': ['GES W8']},
    'Rundumschlag': {'Rang': 'A', 'Voraussetzungen': ['STÄ W8', 'Kämpfen W8']},
    'Kontrollierter Rundumschlag': {'Rang': 'V', 'Voraussetzungen': ['Rundumschlag']},
    'Schmerzresistenz': {'Rang': 'A', 'Voraussetzungen': ['KON W8']},
    'Stärkere Schmerzresistenz': {'Rang': 'A', 'Voraussetzungen': ['Schmerzresistenz']},
    'Schneller Angriff': {'Rang': 'F', 'Voraussetzungen': ['Kämpfen W8']},
    'Blitzschneller Angriff': {'Rang': 'V', 'Voraussetzungen': ['Schneller Angriff']},
    'Schnellfeuer': {'Rang': 'F', 'Voraussetzungen': ['Schießen W6']},
    'Verbessertes Schnellfeuer': {'Rang': 'V', 'Voraussetzungen': ['Schnellfeuer']},
    'Schwer zu töten': {'Rang': 'A', 'Voraussetzungen': ['WIL W8']},
    'Wirklich schwer zu töten': {'Rang': 'V', 'Voraussetzungen': ['Schwer zu töten']},
    'Volles Rohr!': {'Rang': 'F', 'Voraussetzungen': ['Schießen W8']},
    'Volltreffer': {'Rang': 'WC', 'Voraussetzungen': ['A', 'Athletik oder Schießen W8']}
}
anfuehrer_talente = {
    'Anführer': {'Rang': 'A', 'Voraussetzungen': ['VER W6']},
    'Großer Anführer': {'Rang': 'F', 'Voraussetzungen': ['Anführer']},
    'Anheizen': {'Rang': 'V', 'Voraussetzungen': ['WIL W8', 'Anführer']},
    'Geborener Anführer': {'Rang': 'F', 'Voraussetzungen': ['WIL W8', 'Anführer']},
    'Haltet die Stellung!': {'Rang': 'F', 'Voraussetzungen': ['VER W8', 'Anführer']},
    'Inspirieren': {'Rang': 'F', 'Voraussetzungen': ['Anführer']},
    'Taktiker': {'Rang': 'F', 'Voraussetzungen': ['VER W8', 'Anführer', 'Kriegskunst W6']},
    'Meistertaktiker': {'Rang': 'V', 'Voraussetzungen': ['Taktiker']}
}
macht_talente = {
    'Artefakterschaffer': {'Rang': 'F', 'Voraussetzungen': ['AH']},
    'Bastler': {'Rang': 'F', 'Voraussetzungen': ['AH (Verrückte Wissenschaft)', 'Verrückte Wissenschaft W6']},
    'Energieschub': {'Rang': 'WC', 'Voraussetzungen': ['A', 'Arkane Fertigkeit W8', 'AH']},
    'Heiliger/Unheiliger Krieger': {'Rang': 'F', 'Voraussetzungen': ['AH (Wunder)', 'Glaube W6']},
    'Kanalisieren': {'Rang': 'F', 'Voraussetzungen': ['AH']},
    'Konzentration': {'Rang': 'F', 'Voraussetzungen': ['AH']},
    'Machtpunkte': {'Rang': 'A', 'Voraussetzungen': ['AH']},
    'Mentalist': {'Rang': 'F', 'Voraussetzungen': ['AH (Psionik)', 'Psionik W6']},
    'Neue Mächte': {'Rang': 'A', 'Voraussetzungen': ['AH']},
    'Schnelle Machtregeneration': {'Rang': 'F', 'Voraussetzungen': ['WIL W6', 'AH']},
    'Schnellere Machtregeneration': {'Rang': 'V', 'Voraussetzungen': ['Schnelle Machtregeneration']},
    'Seelenentzug': {'Rang': 'F', 'Voraussetzungen': ['AH', 'arkane Fertigkeit W10']},
    'Zauberer': {'Rang': 'F', 'Voraussetzungen': ['AH (Magie)', 'Zaubern W6']},
    'Zusätzliche Anstrengung': {'Rang': 'F', 'Voraussetzungen': ['AH (Begabt)', 'Fokus W6']}
}
experten_talente = {
    'Akrobat': {'Rang': 'A', 'Voraussetzungen': ['GES W8', 'Athletik W8']},
    'Kampfakrobat': {'Rang': 'F', 'Voraussetzungen': ['Akrobat']},
    'Alleskönner': {'Rang': 'A', 'Voraussetzungen': ['VER W10']},
    'Ass am Steuer': {'Rang': 'A', 'Voraussetzungen': ['GES W8']},
    'Assassine': {'Rang': 'A', 'Voraussetzungen': ['GES W8', 'Kämpfen W6', 'Heimlichkeit W8']},
    'Dieb': {'Rang': 'A', 'Voraussetzungen': ['GES W8', 'Heimlichkeit W6', 'Diebeskunst W6']},
    'Ermittler': {'Rang': 'A', 'Voraussetzungen': ['Recherche W8', 'VER W8']},
    'Gelehrter': {'Rang': 'A', 'Voraussetzungen': ['Recherche W8']},
    'McGyver': {'Rang': 'A', 'Voraussetzungen': ['VER W6', 'Reparieren W8', 'Wahrnehmung W8']},
    'Naturbursche': {'Rang': 'A', 'Voraussetzungen': ['WIL W6', 'Überleben W8']},
    'Reparaturgenie': {'Rang': 'A', 'Voraussetzungen': ['Reparieren W8']},
    'Soldat': {'Rang': 'A', 'Voraussetzungen': ['WIL W6', 'KON W6']}
}
sozial_talente = {
    'Aufwiegler': {'Rang': 'F', 'Voraussetzungen': ['Willenskraft W8']},
    'Bedrohlich': {'Rang': 'A', 'Voraussetzungen': []},
    'Beziehungen': {'Rang': 'A', 'Voraussetzungen': []},
    'Ermutigen': {'Rang': 'A', 'Voraussetzungen': ['WIL W8']},
    'Erniedrigen': {'Rang': 'A', 'Voraussetzungen': ['Provozieren W8']},
    'Erzürnen': {'Rang': 'A', 'Voraussetzungen': ['Provozieren W6']},
    'Gassenwissen': {'Rang': 'A', 'Voraussetzungen': ['VER W6']},
    'Konter': {'Rang': 'A', 'Voraussetzungen': ['Provozieren W6']},
    'Rampensau': {'Rang': 'A', 'Voraussetzungen': ['WIL W8']},
    'Echte Rampensau': {'Rang': 'F', 'Voraussetzungen': ['Rampensau']},
    'Selbstlos': {'Rang': 'WC', 'Voraussetzungen': ['WIL W8']},
    'Starker Wille': {'Rang': 'A', 'Voraussetzungen': ['WIL W8']},
    'Eiserner Wille': {'Rang': 'A', 'Voraussetzungen': ['Starker Wille']},
    'Verlässlich': {'Rang': 'A', 'Voraussetzungen': ['WIL W8']}
}
uebersinnliche_talente = {
    'Auserwählter': {'Rang': 'A', 'Voraussetzungen': ['WIL W8', 'Kämpfen W6']},
    'Chi': {'Rang': 'V', 'Voraussetzungen': ['Kampfkunstmeister']},
    'Heiler': {'Rang': 'A', 'Voraussetzungen': ['WIL W8']},
    'Mut in Flaschen': {'Rang': 'A', 'Voraussetzungen': ['KON W8']},
    'Sammler': {'Rang': 'A', 'Voraussetzungen': ['Glück']},
    'Sechster Sinn': {'Rang': 'A', 'Voraussetzungen': []},
    'Tierempathie': {'Rang': 'A', 'Voraussetzungen': []},
    'Tiermeister': {'Rang': 'A', 'Voraussetzungen': ['WIL W8']}
}
legendaere_talente = {
    'Gefolgsleute': {'Rang': 'L', 'Voraussetzungen': ['WC']},
    'Handlanger': {'Rang': 'L', 'Voraussetzungen': ['WC']},
    'Profi': {'Rang': 'L', 'Voraussetzungen': ['W12 in Eigenschaft']},
    'Experte': {'Rang': 'L', 'Voraussetzungen': ['Profi in Eigenschaft']},
    'Meister': {'Rang': 'L', 'Voraussetzungen': ['WC', 'Experte in Eigenschaft']},
    'Waffenmeister': {'Rang': 'L', 'Voraussetzungen': ['Kämpfen W12']},
    'Meister aller Waffen': {'Rang': 'L', 'Voraussetzungen': ['Waffenmeister']},
    'Zäh wie Leder': {'Rang': 'L', 'Voraussetzungen': ['K W8']},
    'Zäher als Leder': {'Rang': 'L', 'Voraussetzungen': ['Zäh wie Leder', 'KON W12']}
}
handicaps = {
    'Alt': {'Stufe':'schwer'},
    'Analphabet': {'Stufe':'leicht'},
    'Angetrieben': {'Stufe':'leicht'},
    'Angetrieben': {'Stufe':'schwer'},
    'Angewohnheit': {'Stufe':'leicht'},
    'Angewohnheit': {'Stufe':'schwer'},
    'Arm': {'Stufe':'leicht'},
    'Arrogant': {'Stufe':'schwer'},
    'Außenseiter': {'Stufe':'leicht'},
    'Außenseiter': {'Stufe':'schwer'},
    'Beschämt': {'Stufe':'leicht'},
    'Beschämt': {'Stufe':'schwer'},
    'Blind': {'Stufe':'schwer'},
    'Blutrünstig': {'Stufe':'schwer'},
    'Dünnhäutig': {'Stufe':'leicht'},
    'Dünnhäutig': {'Stufe':'schwer'},
    'Ehrenkodex': {'Stufe':'schwer'},
    'Eifersüchtig': {'Stufe':'leicht'},
    'Eifersüchtig': {'Stufe':'schwer'},
    'Einarmig': {'Stufe':'schwer'},
    'Einäugig': {'Stufe':'schwer'},
    'Feige': {'Stufe':'schwer'},
    'Feind': {'Stufe':'leicht'},
    'Feind': {'Stufe':'schwer'},
    'Fettleibig': {'Stufe':'leicht'},
    'Fies': {'Stufe':'leicht'},
    'Geheimnis': {'Stufe':'leicht'},
    'Geheimnis': {'Stufe':'schwer'},
    'Gesucht': {'Stufe':'leicht'},
    'Gesucht': {'Stufe':'schwer'},
    'Gierig': {'Stufe':'leicht'},
    'Große Klappe': {'Stufe':'leicht'},
    'Hässlich': {'Stufe':'leicht'},
    'Hässlich': {'Stufe':'schwer'},
    'Heldenhaft': {'Stufe':'schwer'},
    'Impulsiv': {'Stufe':'schwer'},
    'Jung': {'Stufe':'leicht'},
    'Jung': {'Stufe':'schwer'},
    'Klein': {'Stufe':'leicht'},
    'Kränklich': {'Stufe':'leicht'},
    'Langsam': {'Stufe':'leicht'},
    'Langsam': {'Stufe':'schwer'},
    'Lebensaufgabe': {'Stufe':'leicht'},
    'Loyal': {'Stufe':'leicht'},
    'Misstrauisch': {'Stufe':'leicht'},
    'Misstrauisch': {'Stufe':'schwer'},
    'Neugierig': {'Stufe':'schwer'},
    'Nichtschwimmer': {'Stufe':'leicht'},
    'Pazifist': {'Stufe':'leicht'},
    'Pazifist': {'Stufe':'schwer'},
    'Pech': {'Stufe':'schwer'},
    'Phobie': {'Stufe':'leicht'},
    'Phobie': {'Stufe':'schwer'},
    'Rachsüchtig': {'Stufe':'leicht'},
    'Rachsüchtig': {'Stufe':'schwer'},
    'Sanftmütig': {'Stufe':'leicht'},
    'Schlechte Augen': {'Stufe':'leicht'},
    'Schlechte Augen': {'Stufe':'schwer'},
    'Schwerhörig': {'Stufe':'leicht'},
    'Schwerhörig': {'Stufe':'schwer'},
    'Schwerzüngig': {'Stufe':'schwer'},
    'Schwur': {'Stufe':'leicht'},
    'Schwur': {'Stufe':'schwer'},
    'Skrupellos': {'Stufe':'leicht'},
    'Skrupellos': {'Stufe':'schwer'},
    'Stumm': {'Stufe':'schwer'},
    'Stur': {'Stufe':'leicht'},
    'Tick': {'Stufe':'leicht'},
    'Tollpatschig': {'Stufe':'schwer'},
    'Übermütig': {'Stufe':'schwer'},
    'Verpeilt': {'Stufe':'schwer'}
    }
nahkampf_waffe = {
    'Axt, Handbeil': {'Reichweite': 'nah', 'Schaden': 'Stä+W6', 'Mindeststärke': 'W6', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 1, 'Kosten': 100, 'Anmerkungen': '-'},
    'Axt, Kriegsbeil': {'Reichweite': 'nah', 'Schaden': 'Stä+W8', 'Mindeststärke': 'W8', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 2, 'Kosten': 300, 'Anmerkungen': '—'},
    'Axt, Zweihandaxt': {'Reichweite': 'nah', 'Schaden': 'Stä+W10', 'Mindeststärke': 'W10', 'PB': 2, 'FR': '-', 'Schuss': '-', 'Gewicht': 3.5, 'Kosten': 400, 'Anmerkungen': 'Parade –1, Zweihändig'},
    'Dolch/Messer': {'Reichweite': 'nah', 'Schaden': 'Stä+W4', 'Mindeststärke': 'W4', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 0.5, 'Kosten': 25, 'Anmerkungen': '—'},
    'Hellebarde': {'Reichweite': 'nah', 'Schaden': 'Stä+W8', 'Mindeststärke': 'W8', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 3, 'Kosten': 250, 'Anmerkungen': 'Reichweite 1, Zweihändig'},
    'Kampfstab': {'Reichweite': 'nah', 'Schaden': 'Stä+W4', 'Mindeststärke': 'W4', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 2, 'Kosten': 10, 'Anmerkungen': 'Parade +1, Reichweite 1, Zweihändig'},
    'Katana': {'Reichweite': 'nah', 'Schaden': 'Stä+W6+1', 'Mindeststärke': 'W6', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 1.5, 'Kosten': 1000, 'Anmerkungen': 'Zweihändig'},
    'Keule, Leicht': {'Reichweite': 'nah', 'Schaden': 'Stä+W4', 'Mindeststärke': 'W4', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 1, 'Kosten': 25, 'Anmerkungen': '-'},
    'Keule, Schwer': {'Reichweite': 'nah', 'Schaden': 'Stä+W6', 'Mindeststärke': 'W6', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 2.5, 'Kosten': 50, 'Anmerkungen': '-'},
    'Kriegshammer': {'Reichweite': 'nah', 'Schaden': 'Stä+W6', 'Mindeststärke': 'W6', 'PB': 1, 'FR': '-', 'Schuss': '-', 'Gewicht': 1, 'Kosten': 250, 'Anmerkungen': '-'},
    'Lanze': {'Reichweite': 'nah', 'Schaden': 'Stä+W8', 'Mindeststärke': 'W8', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 3, 'Kosten': 300, 'Anmerkungen': 'PB 2 Sturmangriff, Reichweite 2, berittener Kampf'},
    'Morgenstern': {'Schaden': 'Stä+W6', 'Mindeststärke': 'W6', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 1.5, 'Kosten': 200, 'Anmerkungen': 'ignoriert Schildboni'},
    'Rapier': {'Reichweite': 'nah', 'Schaden': 'Stä+W4', 'Mindeststärke': 'W4', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 1, 'Kosten': 150, 'Anmerkungen': 'Parade +1'},
    'Schwert, Kurzschwert': {'Reichweite': 'nah', 'Schaden': 'Stä+W6', 'Mindeststärke': 'W6', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 1, 'Kosten': 100, 'Anmerkungen': '-'},
    'Schwert, Langschwert': {'Reichweite': 'nah', 'Schaden': 'Stä+W8', 'Mindeststärke': 'W8', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 1.5, 'Kosten': 300, 'Anmerkungen': '-'},
    'Schwert, Zweihandschwert': {'Reichweite': 'nah', 'Schaden': 'Stä+W10', 'Mindeststärke': 'W10', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 3, 'Kosten': 400, 'Anmerkungen': 'Zweihändig'},
    'Speer': {'Reichweite': 'nah', 'Schaden': 'Stä+W6', 'Mindeststärke': 'W6', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 1.5, 'Kosten': 100, 'Anmerkungen': 'Reichweite 1, Parade +1 wenn zweihändig'},
    'Spieß': {'Reichweite': 'nah', 'Schaden': 'Stä+W8', 'Mindeststärke': 'W8', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 9, 'Kosten': 400, 'Anmerkungen': 'Reichweite 2, Zweihändig'},
    'Streitkolben': {'Reichweite': 'nah', 'Schaden': 'Stä+W6', 'Mindeststärke': 'W6', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 2, 'Kosten': 100, 'Anmerkungen': '—'},
    'Zweihandhammer': {'Reichweite': 'nah', 'Schaden': 'Stä+W10', 'Mindeststärke': 'W10', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 5, 'Kosten': 400, 'Anmerkungen': 'Zweihändig, +2 Schaden/Gegenstände (Seite 100)'},
    'Bangstick': {'Reichweite': 'nah', 'Schaden': '3W6', 'Mindeststärke': 'W6', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 1, 'Kosten': 5, 'Anmerkungen': '-'},
    'Bajonett': {'Reichweite': 'nah', 'Schaden': 'Stä+W4', 'Mindeststärke': 'W4', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 0.5, 'Kosten': 25, 'Anmerkungen': 'Stä+W6 und Parade +1 am Gewehr, Reichweite 1, Zweihändig'},
    'Kettensäge': {'Reichweite': 'nah', 'Schaden': '2W6+4', 'Mindeststärke': 'W6', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 10, 'Kosten': 200, 'Anmerkungen': 'Kritischer Fehlschlag Eigentrffer'},
    'Schlagring': {'Reichweite': 'nah', 'Schaden': 'Stä+W4', 'Mindeststärke': 'W4', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 0.5, 'Kosten': 20, 'Anmerkungen': '-'},
    'Schlagstock': {'Reichweite': 'nah', 'Schaden': 'Stä+W4', 'Mindeststärke': 'W4', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 0.5, 'Kosten': 10, 'Anmerkungen': '-'},
    'Springmesser': {'Reichweite': 'nah', 'Schaden': 'Stä+W4', 'Mindeststärke': 'W4', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 0.25, 'Kosten': 10, 'Anmerkungen': '-'},
    'Überlebensmesser': {'Reichweite': 'nah', 'Schaden': 'Stä+W4', 'Mindeststärke': 'W4', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 0.5, 'Kosten': 50, 'Anmerkungen': '+1 auf Überleben'},
    'Molekularmesser': {'Reichweite': 'nah', 'Schaden': 'Stä+W4+2', 'Mindeststärke': 'W4', 'PB': 2, 'FR': '-', 'Schuss': '-', 'Gewicht': 0.25, 'Kosten': 250, 'Anmerkungen': 'nicht werfen'},
    'Molekularschwert': {'Reichweite': 'nah', 'Schaden': 'Stä+W8+2', 'Mindeststärke': 'W6', 'PB': 4, 'FR': '-', 'Schuss': '-', 'Gewicht': 1, 'Kosten': 500, 'Anmerkungen': '-'},
    'Laserschwert': {'Reichweite': 'nah', 'Schaden': 'Stä+W6+8', 'Mindeststärke': 'W4', 'PB': 12, 'FR': '-', 'Schuss': '-', 'Gewicht': 1, 'Kosten': 1000, 'Anmerkungen': '-'}
}
fernkampf_waffe = {
    'Browning Automatic Rifle (BAR) (.30-06)': {'Reichweite': '20/40/60', 'Schaden': '2W8', 'PB': 2, 'FR': 3, 'Schuss': 20, 'Mindeststärke': 'W8', 'Gewicht': 8.5, 'Kosten': 300},
    'Gatling (.45)': {'Reichweite': '24/48/96', 'Schaden': '2W8', 'PB': 2, 'FR': 3, 'Schuss': 100, 'Mindeststärke': '-', 'Gewicht': 85, 'Kosten': 500},
    'Minigun (7.62mm)': {'Reichweite': '30/60/120', 'Schaden': '2W8+1', 'PB': 2, 'FR': 5, 'Schuss': 4000, 'Mindeststärke': 'W10', 'Gewicht': 42.5, 'Kosten': 100000},
    'M2 Browning (.50 Cal)': {'Reichweite': '50/100/200', 'Schaden': '2W10', 'PB': 4, 'FR': 3, 'Schuss': 200, 'Mindeststärke': '-', 'Gewicht': 42, 'Kosten': 1500},
    'M60 (7.62mm)': {'Reichweite': '30/60/120','Schaden': '2W8+1', 'PB': 2, 'FR': 3, 'Schuss': 100, 'Mindeststärke': 'W8', 'Gewicht': 16.5, 'Kosten': 6000},
    'MG42 (7.92mm)': { 'Reichweite': '30/60/120','Schaden': '2W8+1', 'PB': 2, 'FR': 4, 'Schuss': 200, 'Mindeststärke': 'W10', 'Gewicht': 13, 'Kosten': 750},
    'SAW (5.56mm)': { 'Reichweite': '30/60/120', 'Schaden': '2W8', 'PB': 2, 'FR': 4, 'Schuss': 200, 'Mindeststärke': 'W8', 'Gewicht': 10, 'Kosten': 4000},
    'Pistole': { 'Reichweite': '15/30/60', 'Schaden': '2W6', 'PB': 2, 'FR': 1, 'Schuss': 50, 'Mindeststärke': 'W4', 'Gewicht': 1, 'Kosten': 250},
    'Maschinenpistole': { 'Reichweite': '15/30/60', 'Schaden': '2W6', 'PB': 2, 'FR': 4, 'Schuss': 100, 'Mindeststärke': 'W4', 'Gewicht': 2, 'Kosten': 500},
    'Gewehr': { 'Reichweite': '30/60/120', 'Schaden': '3W6', 'PB': 2, 'FR': 3, 'Schuss': 100, 'Mindeststärke': 'W6', 'Gewicht': 4, 'Kosten': 700},
    'Gatling-Laser': { 'Reichweite': '50/100/200', 'Schaden': '3W6+4', 'PB': 2, 'FR': 4, 'Schuss': 800, 'Mindeststärke': 'W8', 'Gewicht': 10, 'Kosten': 1000}
}
spezielle_waffe = {
    'Axt, Handbeil': {'Reichweite': 'nah', 'Schaden': 'Stä+W6', 'Mindeststärke': 'W6', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 1, 'Kosten': 100, 'Anmerkungen': '-'},
    'Axt, Kriegsbeil': {'Reichweite': 'nah', 'Schaden': 'Stä+W8', 'Mindeststärke': 'W8', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 2, 'Kosten': 300, 'Anmerkungen': '—'},
    # 'Kanonen': {
    #     'Kanone (12 Pfünder)': {'Reichweite': 'Nach Munitionsart', 'Schaden': '—', 'PB': '—', 'FR': '—', 'Flächenschablone': '—', 'Gewicht': 600, 'Kosten': 10000},
    #     'Kartätsche': {'Reichweite': '24″ Pfad', 'Schaden': '2W6', 'PB': '—', 'FR': '1', 'Flächenschablone': 'MFS', 'Gewicht': 50, 'Kosten': 50},
    #     'Rundgeschoss': {'Reichweite': '50/100/200', 'Schaden': '3W6+1', 'PB': 4, 'FR': '1', 'Flächenschablone': '—', 'Gewicht': 50, 'Kosten': 50},
    #     'Schrapnell': {'Reichweite': '50/100/200', 'Schaden': '3W6', 'PB': '—', 'FR': '1', 'Flächenschablone': 'MFS', 'Gewicht': 50, 'Kosten': 50},
    # },
    # 'Katapulte': {
    #     'Katapult': {'Reichweite': '24/48/96', 'Schaden': '3W6', 'PB': 4, 'FR': 'Speziell', 'Flächenschablone': 'MFS', 'Gewicht': 10000, 'Kosten': 10000},
    #     'Trebuchet': {'Reichweite': '30/60/120', 'Schaden': '3W8', 'PB': 4, 'FR': 'Speziell', 'Flächenschablone': 'MFS', 'Gewicht': 50000, 'Kosten': 50000},
    # },
    # 'Flammenwerfer': {
    #     'Flammenwerfer': {'Reichweite': 'Kegelschablone', 'Schaden': '3W6', 'PB': '—', 'FR': 1, 'Schuss': 10, 'Mindeststärke': 'W8', 'Gewicht': 35, 'Kosten': 300},
    # },
    # 'Granaten': {
    #     'Mk II (Pineapple, Zweiter Weltkrieg)': {'Reichweite': '4/8/16', 'Schaden': '3W6', 'PB': '—', 'FR': '—', 'Flächenschablone': 'MFS', 'Gewicht': 0.5, 'Kosten': 40},
    #     'Stielhandgranate (Potato Masher, Zweiter Weltkrieg)': {'Reichweite': '5/10/20', 'Schaden': '3W6–2', 'PB': '—', 'FR': '—', 'Flächenschablone': 'MFS', 'Gewicht': 1, 'Kosten': 50},
    #     'Mk67 (Modern)': {'Reichweite': '5/10/20', 'Schaden': '3W6', 'PB': '—', 'FR': '—', 'Flächenschablone': 'MFS', 'Gewicht': 0.5, 'Kosten': 50},
    #     'Rauchgranate': {'Reichweite': '5/10/20', 'Schaden': '—', 'PB': '—', 'FR': '—', 'Flächenschablone': 'GFS', 'Gewicht': 0.5, 'Kosten': 50},
    #     'Betäubungsgranate': {'Reichweite': '5/10/20', 'Schaden': '—', 'PB': '—', 'FR': '—', 'Flächenschablone': 'GFS', 'Gewicht': 0.5, 'Kosten': 50},
    # },
    # 'Minen': {
    #     'Antipersonenmine': {'Reichweite': '—', 'Schaden': '2W6+2', 'PB': '—', 'FR': '—', 'Flächenschablone': 'KFS', 'Gewicht': 5, 'Kosten': 100},
    #     'Panzerabwehrmine': {'Reichweite': '—', 'Schaden': '4W6', 'PB': '—', 'FR': '—', 'Flächenschablone': 'MFS', 'Gewicht': 10, 'Kosten': 200},
    #     'Bouncing Betty': {'Reichweite': '—', 'Schaden': '3W6', 'PB': '—', 'FR': '—', 'Flächenschablone': 'KFS', 'Gewicht': 4.5, 'Kosten': 125},
    #     'Claymore-Mine': {'Reichweite': '—', 'Schaden': '3W6', 'PB': '—', 'FR': '—', 'Flächenschablone': 'Speziell', 'Gewicht': 2, 'Kosten': 75},
    # },
    # 'Raketen': {
    #     'TOW': {'Reichweite': '75/150/300', 'Schaden': '5W10', 'PB': 34, 'FR': 1, 'Flächenschablone': 'MFS', 'Gewicht': 104, 'Kosten': 60000},
    #     'Hellfire': {'Reichweite': '150/300/600', 'Schaden': '5W10', 'PB': 40, 'FR': 'Speziell', 'Flächenschablone': 'MFS', 'Gewicht': 50, 'Kosten': 115000},
    #     'Sidewinder': {'Reichweite': '100/200/400', 'Schaden': '4W8', 'PB': 6, 'FR': '—', 'Flächenschablone': 'KFS', 'Gewicht': 94, 'Kosten': 600000},
    #     'Sparrow': {'Reichweite': '150/300/600', 'Schaden': '5W8', 'PB': 6, 'FR': '—', 'Flächenschablone': 'KFS', 'Gewicht': 309, 'Kosten': 125000},
    # },
    # 'Raketenwerfer und Torpedos': {
    #     'AT-4': {'Reichweite': '24/48/96', 'Schaden': '4W8+2', 'PB': 24, 'FR': 1, 'Flächenschablone': 'MFS', 'Gewicht': 7.5, 'Kosten': 1500},
    #     'Bazooka': {'Reichweite': '24/48/96', 'Schaden': '4W8', 'PB': 8, 'FR': 1, 'Flächenschablone': 'MFS', 'Gewicht': 6, 'Kosten': 500},
    #     'M203 40MM': {'Reichweite': '24/48/96', 'Schaden': '4W8', 'PB': '—', 'FR': 1, 'Flächenschablone': 'MFS', 'Gewicht': 1.5, 'Kosten': 1500},
    #     'M72 Law': {'Reichweite': '24/48/96', 'Schaden': '4W8+2', 'PB': 22, 'FR': 1, 'Flächenschablone': 'MFS', 'Gewicht': 2.5, 'Kosten': 750},
    #     'Panzerschreck': {'Reichweite': '15/30/60', 'Schaden': '4W8', 'PB': 12, 'FR': 1, 'Flächenschablone': 'MFS', 'Gewicht': 10, 'Kosten': 1000},
    #     'Torpedo': {'Reichweite': '300/600/1200', 'Schaden': '8W10', 'PB': 22, 'FR': 1, 'Flächenschablone': 'KFS', 'Gewicht': 1500, 'Kosten': 500000},
    }
fahrzeug_waffe = {
    'Axt, Handbeil': {'Reichweite': 'nah', 'Schaden': 'Stä+W6', 'Mindeststärke': 'W6', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 1, 'Kosten': 100, 'Anmerkungen': '-'},
    'Axt, Kriegsbeil': {'Reichweite': 'nah', 'Schaden': 'Stä+W8', 'Mindeststärke': 'W8', 'PB': '-', 'FR': '-', 'Schuss': '-', 'Gewicht': 2, 'Kosten': 300, 'Anmerkungen': '—'},
    # 'Mittleres Maschinengewehr': {'Reichweite': '30/60/120', 'PB-Geschosse': '2W8+1, PB 2', 'HE-Geschosse': '—', 'FR': 3, 'Kosten': 750},
    # 'Schweres Maschinengewehr': {'Reichweite': '50/100/200', 'PB-Geschosse': '2W10, PB 4', 'HE-Geschosse': '—', 'FR': 3, 'Kosten': 1000},
    # 'Schwerer Flammenwerfer': {'Reichweite': 'Kegel oder MFS', 'PB-Geschosse': '—', 'HE-Geschosse': '3W8', 'FR': 1, 'Kosten': 1000},
    # '20mm-Kanone': {'Reichweite': '50/100/200', 'PB-Geschosse': '2W12, PB 4', 'HE-Geschosse': '—', 'FR': 4, 'Kosten': 50000},
    # '25mm-Kanone': {'Reichweite': '50/100/200', 'PB-Geschosse': '3W8, PB 4', 'HE-Geschosse': '—', 'FR': 3, 'Kosten': 75000},
    # '30mm-Kanone': {'Reichweite': '50/100/200', 'PB-Geschosse': '3W8, PB 6', 'HE-Geschosse': '—', 'FR': 3, 'Kosten': 200000},
    # '40mm-Kanone': {'Reichweite': '75/150/300', 'PB-Geschosse': '4W8, PB 5', 'HE-Geschosse': '3W8, PB 2, MFS', 'FR': 4, 'Kosten': 200000},
    # '2-Pfünder-Panzerabwehrkanone': {'Reichweite': '75/150/300', 'PB-Geschosse': '4W8, PB 5', 'HE-Geschosse': '3W6, PB 2, MFS', 'FR': 1, 'Kosten': 75000},
    # '37mm-Panzerabwehrkanone': {'Reichweite': '50/100/200', 'PB-Geschosse': '4W8, PB 3', 'HE-Geschosse': '4W6, PB 3, MFS', 'FR': 1, 'Kosten': 100000},
    # '57mm-Panzerabwehrkanone': {'Reichweite': '75/150/300', 'PB-Geschosse': '4W8, PB 5', 'HE-Geschosse': '3W8, PB 3, MFS', 'FR': 1, 'Kosten': 150000},
    # '75mm-Panzerkanone': {'Reichweite': '75/150/300', 'PB-Geschosse': '4W10, PB 6', 'HE-Geschosse': '3W8, PB 3, MFS', 'FR': 1, 'Kosten': 250000},
    # '76mm-Panzerkanone': {'Reichweite': '75/150/300', 'PB-Geschosse': '4W10, PB 10', 'HE-Geschosse': '3W8, PB 5, MFS', 'FR': 1, 'Kosten': 300000},
    # '88mm-Panzerkanone': {'Reichweite': '100/200/400', 'PB-Geschosse': '4W10+1, PB 16', 'HE-Geschosse': '4W8, PB 8, MFS', 'FR': 1, 'Kosten': 500000},
    # '120mm-Panzerkanone': {'Reichweite': '100/200/400', 'PB-Geschosse': '5W10, PB 31', 'HE-Geschosse': '4W8, PB 17, MFS', 'FR': 1, 'Kosten': 800000},
    # '125mm-Panzerkanone': {'Reichweite': '100/200/400', 'PB-Geschosse': '5W10, PB 30', 'HE-Geschosse': '4W8, PB 15, MFS', 'FR': 1, 'Kosten': 1000000},
    # 'Futuristisch': {
    #     'Gatling-Laser': {'Reichweite': '50/100/200', 'PB-Geschosse': '3W6+4, PB 4', 'HE-Geschosse': '—', 'FR': 4, 'Kosten': 1000},
    #     'Schwerer Laser': {'Reichweite': '150/300/600', 'PB-Geschosse': '4W10, PB 30', 'HE-Geschosse': '—', 'FR': 1, 'Kosten': 1000000},
    }
ausruestung = {
    'Pferd': {'Kosten': 300, 'Gewicht': 0},
    'Streitross': {'Kosten': 750, 'Gewicht': 0},
    'Sattel': {'Kosten': 10, 'Gewicht': 5},
    'Verzierter Sattel': {'Kosten': 50, 'Gewicht': 5},
    'Brechstange': {'Kosten': 10, 'Gewicht': 1},
    'Dietriche': {'Kosten': 200, 'Gewicht': 0.5},
    'Erste-Hilfe-Tasche': {'Kosten': 10, 'Gewicht': 0.5},
    'Fackel': {'Kosten': 5, 'Gewicht': 0.5},
    'Feuerstein und Stahl': {'Kosten': 3, 'Gewicht': 0.5},
    'Feuerzeug': {'Kosten': 2, 'Gewicht': 0},
    'Fläschchen (Keramik)': {'Kosten': 5, 'Gewicht': 0.5},
    'Hammer': {'Kosten': 10, 'Gewicht': 0.5},    
    'Handschellen': {'Kosten': 15, 'Gewicht': 1},
    'Kamera (Einweg)': {'Kosten': 10, 'Gewicht': 0.5},
    'Kamera (normal)': {'Kosten': 75, 'Gewicht': 1},
    'Kamera (digital)': {'Kosten': 300, 'Gewicht': 0.5},
    'Kerze (eine Stunde, 2" Radius)': {'Kosten': 1, 'Gewicht': 0.5},
    'Köcher (für 20 Pfeile/Bolzen)': {'Kosten': 25, 'Gewicht': 1},
    'Laterne (4 Stunden, 4" Radius)': {'Kosten': 25, 'Gewicht': 1.5},
    'Öl (für Laterne, 0,5 Liter)': {'Kosten': 2, 'Gewicht': 0.5},
    'Regenschirm': {'Kosten': 5, 'Gewicht': 1},
    'Rucksack': {'Kosten': 50, 'Gewicht': 1},
    'Sanitätskoffer': {'Kosten': 100, 'Gewicht': 2},
    'Schaufel': {'Kosten': 5, 'Gewicht': 2.5},
    'Schlafsack (winterfest)': {'Kosten': 25, 'Gewicht': 2},
    'Schutzbrille': {'Kosten': 20, 'Gewicht': 0.5},
    'Seife': {'Kosten': 1, 'Gewicht': 0.1},
    'Seil, Hanf (10" / 20 m)': {'Kosten': 10, 'Gewicht': 7.5},
    'Seil, Nylon (10" / 20 m)': {'Kosten': 10, 'Gewicht': 1.5},
    'Taschenlampe (10" Strahl)': {'Kosten': 20, 'Gewicht': 1.5},
    'Trillerpfeife': {'Kosten': 2, 'Gewicht': 0},
    'Wasserflasche (Wasserschlauch)': {'Kosten': 5, 'Gewicht': 0.5},
    'Werkzeugkoffer': {'Kosten': 200, 'Gewicht': 2.5},
    'Wetzstein': {'Kosten': 5, 'Gewicht': 0.5},
    'Wolldecke': {'Kosten': 10, 'Gewicht': 2},
    'Wurfanker': {'Kosten': 100, 'Gewicht': 1},
    'Laser-/Rotpunktvisier': {'Kosten': 150, 'Gewicht': 0.5},
    'Zielfernrohr': {'Kosten': 100, 'Gewicht': 1},
    'Zweibein/Dreibein': {'Kosten': 100, 'Gewicht': 1},
    'Kleidung, Alltag': {'Kosten': 20, 'Gewicht': 1},
    'Kleidung, formell': {'Kosten': 200, 'Gewicht': 1.5},
    'Tarnkleidung': {'Kosten': 20, 'Gewicht': 1.5},
    'Wanderstiefel': {'Kosten': 100, 'Gewicht': 1},
    'Winterkleidung (Mantel/Parka)': {'Kosten': 200, 'Gewicht': 1.5},
    'Winterstiefel': {'Kosten': 100, 'Gewicht': 0.5},
    'Desktop': {'Kosten': 800, 'Gewicht': 10},
    'GPS': {'Kosten': 250, 'Gewicht': 0.5},
    'Laptop': {'Kosten': 1200, 'Gewicht': 2.5},
    'Taschencomputer': {'Kosten': 250, 'Gewicht': 0.5},
    'Pfeile/Bolzen': {'Kosten': 1, 'Gewicht': 1},
    'Patronen (Klein)': {'Kosten': 10, 'Gewicht': 0.5},
    'Patronen (Mittel)': {'Kosten': 20, 'Gewicht': 1},
    'Patronen (Groß)': {'Kosten': 50, 'Gewicht': 7.5},
    'Laserbatterien (Pistole)': {'Kosten': 20, 'Gewicht': 0.1},
    'Laserbatterien (Gewehr, Maschinenpistole)': {'Kosten': 20, 'Gewicht': 0.25},
    'Gattling': {'Kosten': 50, 'Gewicht': 2},
    'Kugel (mit Schwarzpulver)': {'Kosten': 1, 'Gewicht': 0.25},
    'Schrotflinte': {'Kosten': 15, 'Gewicht': 1.5},
    'Flintenlaufgschosse': {'Kosten': 20, 'Gewicht': 1.5},
    'Schleudersteine': {'Kosten': 2, 'Gewicht': 1},
    'Pfefferspray': {'Kosten': 15, 'Gewicht': 0.25},
    'Taser': {'Kosten': 25, 'Gewicht': 0.25},
    'Handy-Abhörer': {'Kosten': 650, 'Gewicht': 2.5},
    'Knopfkamera': {'Kosten': 50, 'Gewicht': 0},
    'Nachtsichtbrille': {'Kosten': 500, 'Gewicht': 1.5},
    'Parabolmikrofon': {'Kosten': 750, 'Gewicht': 2},
    'Senderdetektor': {'Kosten': 525, 'Gewicht': 0.5},
    'Störtelefon': {'Kosten': 150, 'Gewicht': 1},
    'Telefonanzapfung': {'Kosten': 250, 'Gewicht': 0},
    '„Wanze“ (Mikrotransmitter)': {'Kosten': 30, 'Gewicht': 0}
}
ruestung = {
    'Jacke (dünn)': {'Torso': 1, 'Arme': 1, 'Beine': 0, 'Kopf': 0, 'Mindeststärke': 'W4', 'Gewicht': 2.5, 'Kosten': 20},
    'Robe(dünn)': {'Torso': 1, 'Arme': 1, 'Beine': 1, 'Kopf': 0, 'Mindeststärke': 'W4', 'Gewicht': 4, 'Kosten': 30},
    'Beinlinge(dünn)': {'Torso': 0, 'Arme': 0, 'Beine': 1, 'Kopf': 0, 'Mindeststärke': 'W4', 'Gewicht': 2.5, 'Kosten': 20},
    'Kappe(dünn)': {'Torso': 0, 'Arme': 0, 'Beine': 0, 'Kopf': 1, 'Mindeststärke': 'W4', 'Gewicht': 0.5, 'Kosten': 5},
    'Jacke (dick)': {'Torso': 1, 'Arme': 2, 'Beine': 0, 'Kopf': 0, 'Mindeststärke': 'W6', 'Gewicht': 4, 'Kosten': 80},
    'Beinlinge(dick)': {'Torso': 0, 'Arme': 0, 'Beine': 2, 'Kopf': 0, 'Mindeststärke': 'W6', 'Gewicht': 3.5, 'Kosten': 40},
    'Kappe(dick)': {'Torso': 0, 'Arme': 0, 'Beine': 0, 'Kopf': 2, 'Mindeststärke': 'W6', 'Gewicht': 0.5, 'Kosten': 20},
    'Hemd (Kette)': {'Torso': 3, 'Arme': 3, 'Beine': 0, 'Kopf': 0, 'Mindeststärke': 'W8', 'Gewicht': 12.5, 'Kosten': 300},
    'Beinlinge(Kette)': {'Torso': 0, 'Arme': 0, 'Beine': 3, 'Kopf': 0, 'Mindeststärke': 'W8', 'Gewicht': 5, 'Kosten': 150},
    'Helm (Kette)': {'Torso': 0, 'Arme': 0, 'Beine': 0, 'Kopf': 3, 'Mindeststärke': 'W8', 'Gewicht': 2, 'Kosten': 25},
    'Brustharnisch (Bronze)': {'Torso': 3, 'Arme': 0, 'Beine': 0, 'Kopf': 0, 'Mindeststärke': 'W10', 'Gewicht': 6.5, 'Kosten': 80},
    'Armschienen (Bronze)': {'Torso': 0, 'Arme': 3, 'Beine': 0, 'Kopf': 0, 'Mindeststärke': 'W10', 'Gewicht': 2.5, 'Kosten': 40},
    'Beinschienen (Bronze)': {'Torso': 0, 'Arme': 0, 'Beine': 3, 'Kopf': 0, 'Mindeststärke': 'W10', 'Gewicht': 3, 'Kosten': 50},
    'Helm (Bronze)': {'Torso': 0, 'Arme': 0, 'Beine': 0, 'Kopf': 3, 'Mindeststärke': 'W10', 'Gewicht': 3, 'Kosten': 25},
    'Brustharnisch (Platte)': {'Torso': 4, 'Arme': 0, 'Beine': 0, 'Kopf': 0, 'Mindeststärke': 'W10', 'Gewicht': 15, 'Kosten': 500},
    'Armschienen (Platte)': {'Torso': 0, 'Arme': 4, 'Beine': 0, 'Kopf': 0, 'Mindeststärke': 'W10', 'Gewicht': 5, 'Kosten': 200},
    'Beinschienen (Platte)': {'Torso': 0, 'Arme': 0, 'Beine': 4, 'Kopf': 0, 'Mindeststärke': 'W10', 'Gewicht': 5, 'Kosten': 200},
    'Schwerer Helm': {'Torso': 0, 'Arme': 0, 'Beine': 0, 'Kopf': 4, 'Mindeststärke': 'W10', 'Gewicht': 2, 'Kosten': 100},
    'Schwerer Helm, geschlossen': {'Torso': 0, 'Arme': 0, 'Beine': 0, 'Kopf': 4, 'Mindeststärke': 'W10', 'Gewicht': 4, 'Kosten': 200},
    'Splitterschutzjacke': {'Torso': 2, 'Arme': 0, 'Beine': 0, 'Kopf': 0, 'Mindeststärke': 'W6', 'Gewicht': 2.5, 'Kosten': 40},
    'Kevlarweste': {'Torso': 2, 'Arme': 0, 'Beine': 0, 'Kopf': 0, 'Mindeststärke': 'W6', 'Gewicht': 2.5, 'Kosten': 200},
    'Kevlarweste mit Keramikplatten': {'Torso': 4, 'Arme': 0, 'Beine': 0, 'Kopf': 0, 'Mindeststärke': 'W8', 'Gewicht': 8.5, 'Kosten': 500},
    'Kevlarhelm': {'Torso': 0, 'Arme': 0, 'Beine': 0, 'Kopf': 4, 'Mindeststärke': 'W4', 'Gewicht': 2.5, 'Kosten': 80},
    'Bombenschutzanzug': {'Torso': 10, 'Arme': 10, 'Beine': 10, 'Kopf': 10, 'Mindeststärke': 'W12', 'Gewicht': 40, 'Kosten': 25000},
    'Infanteriekampfanzug': {'Torso': 6, 'Arme': 6, 'Beine': 6, 'Kopf': 0, 'Mindeststärke': 'W6', 'Gewicht': 6, 'Kosten': 800},
    'Kampfhelm': {'Torso': 0, 'Arme': 0, 'Beine': 0, 'Kopf': 6, 'Mindeststärke': 'W6', 'Gewicht': 1, 'Kosten': 100}
}
schilde = {
    'Klein': {'Parade': '+1', 'Deckung': '—', 'Mindeststärke': 'W4', 'Gewicht': 2, 'Kosten': 50},
    'Mittel': {'Parade': '+2', 'Deckung': '–2', 'Mindeststärke': 'W6', 'Gewicht': 4, 'Kosten': 100},
    'Groß': {'Parade': '+3', 'Deckung': '–4', 'Mindeststärke': 'W8', 'Gewicht': 6, 'Kosten': 200},
    'Einsatzschild': {'Parade': '+3', 'Deckung': '–4', 'Mindeststärke': 'W4', 'Gewicht': 2.5, 'Kosten': 80},
    'Ballistischer Schild': {'Parade': '+3', 'Deckung': '–4', 'Mindeststärke': 'W6', 'Gewicht': 4.5, 'Kosten': 250},
    'Polymerschild, Klein': {'Parade': '+1', 'Deckung': '—', 'Mindeststärke': 'W4', 'Gewicht': 1, 'Kosten': 200},
    'Polymerschild, Mittel': {'Parade': '+2', 'Deckung': '–2', 'Mindeststärke': 'W4', 'Gewicht': 2, 'Kosten': 300},
    'Polymerschild, Groß': {'Parade': '+3', 'Deckung': '–4', 'Mindeststärke': 'W6', 'Gewicht': 3, 'Kosten': 400}
}
grundfertigkeiten = [
            'Allgemeinwissen* ',
            'Athletik* ',
            'Heimlichkeit* ',
            'Überreden* ',
            'Wahrnehmung* '
    ]