<WaffeDialogContent>:
    orientation: 'vertical'
    spacing: "12dp"
    padding: "12dp"
    size_hint_y: None
    height: "720dp"

    MDTextField:
        id: name_input
        mode: "outlined"
        
        MDTextFieldHintText:
            text: 'Name der Waffe'

    MDSegmentedButton:
        id: typ_segment
        pos_hint: {"center_x": .5}
        
        MDSegmentedButtonItem:
            id: nahkampf_button
            size_hint: None, None
            size: dp(120), dp(40)
            on_release: root.select_typ('Nahkampf')
            selected: True

            MDSegmentButtonLabel:
                text: "Nahkampf"

        MDSegmentedButtonItem:
            id: fernkampf_button
            size_hint: None, None
            size: dp(120), dp(40)
            on_release: root.select_typ('Fernkampf')

            MDSegmentButtonLabel:
                text: "Fernkampf"

    MDTextField:
        id: mindeststaerke_input
        mode: "outlined"
        
        MDTextFieldHintText:
            text: 'Mindeststärke (z.B. W4, W6)'

    MDTextField:
        id: gewicht_input
        mode: "outlined"
        input_filter: 'float'
        
        MDTextFieldHintText:
            text: 'Gewicht'

    MDTextField:
        id: kosten_input
        mode: "outlined"
        input_filter: 'float'
        
        MDTextFieldHintText:
            text: 'Kosten'

    MDTextField:
        id: setting_input
        mode: "outlined"
        
        MDTextFieldHintText:
            text: 'Setting'
            
    MDTextField:
        id: schaden_input
        mode: "outlined"
        
        MDTextFieldHintText:
            text: 'Schaden (z.B. Stä+W8)'

    MDTextField:
        id: reichweite_input
        mode: "outlined"
        
        MDTextFieldHintText:
            text: 'Reichweite'

    MDTextField:
        id: fr_input
        mode: "outlined"
        
        MDTextFieldHintText:
            text: 'Feuerrate (FR)'

    MDTextField:
        id: schuss_input
        mode: "outlined"
        
        MDTextFieldHintText:
            text: 'Schuss'

    MDTextField:
        id: pb_input
        mode: "outlined"
        
        MDTextFieldHintText:
            text: 'Panzerbrechend (PB)'

    MDTextField:
        id: beschreibung_input
        mode: "outlined"
        multiline: True
        
        MDTextFieldHintText:
            text: 'Beschreibung'

<DeleteWaffeDialogContent>:
    orientation: 'vertical'
    spacing: "12dp"
    padding: "12dp"
    size_hint_y: None
    height: "120dp"

    MDDropDownItem:
        id: waffe_dropdown
        pos_hint: {"center_x": .5, "center_y": .5}
        on_release: root.open_menu(self)

        MDDropDownItemText:
            id: selected_waffe_text
            text: "Waffe auswählen"