<CharakterbogenWidget>:
    orientation: 'vertical'
    padding: 10
    spacing: 10

    MDScrollView:
        size_hint: (1, 1)
        do_scroll_x: False
        do_scroll_y: True
        bar_width: dp(15)
        bar_margin: dp(8)
        scroll_wheel_distance: dp(114)

        MDBoxLayout:
            orientation: 'vertical'
            size_hint_y: None
            height: self.minimum_height
            spacing: 10
            padding: 10   

            # Überschrift Profil
            LeftAlignedLabel:
                text: "Charakter"
                font_size: '18sp'
                bold: True
                size_hint_y: None
                height: 30
                spacing: 10
                padding: 10 

            # Profil-Abschnitt, der die Profildaten dynamisch anzeigt
            MDBoxLayout:
                id: profil_section
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 10
                padding: 10    

            # Überschrift Attribute
            LeftAlignedLabel:
                text: "Attribute"
                font_size: '18sp'
                bold: True
                size_hint_y: None
                height: 20
                spacing: 5
                padding: 10 

            MDBoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 5
                padding: 10               

                MDGridLayout:
                    id: attribut_grid
                    cols: 2
                    size_hint_y: None
                    height: self.minimum_height
                    row_default_height: 20
                    spacing: 5  # Entfernt den Abstand zwischen den Widgets
                    padding: 10  # Entfernt die Einrückung

            # Überschrift Fertigkeiten
            LeftAlignedLabel:
                text: "Fertigkeiten"
                font_size: '18sp'
                bold: True
                size_hint_y: None
                height: 20
                spacing: 5
                padding: 10 

            MDBoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 5
                padding: 10   

                MDGridLayout:
                    id: fertigkeit_grid
                    cols: 2
                    size_hint_y: None
                    height: self.minimum_height
                    row_default_height: 20
                    spacing: 5
                    padding: 10

            # Abgeleitete Werte Abschnitt
            LeftAlignedLabel:
                text: "Abgeleitete Werte:"
                font_size: '16sp'
                bold: True
                size_hint_y: None
                height: 10
                spacing: 5
                padding: 10 

            MDBoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 5
                padding: 10   

                MDGridLayout:
                    id: abgeleitete_werte_grid
                    cols: 2
                    size_hint_y: None
                    height: self.minimum_height
                    row_default_height: 20
                    spacing: 5
                    padding: 10 

            # Volk Abschnitt

            MDBoxLayout:
                id: volk_section
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 10
                padding: 10   

            # Handicaps Abschnitt
            LeftAlignedLabel:
                text: "Handicaps:"
                font_size: '18sp'
                bold: True
                size_hint_y: None
                height: 30
                spacing: 10
                padding: 10 

            MDBoxLayout:
                id: handicaps_section
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 10
                padding: 10   

            # Talente Abschnitt
            LeftAlignedLabel:
                text: "Talente:"
                font_size: '18sp'
                bold: True
                size_hint_y: None
                height: 30
                spacing: 10
                padding: 10 

            MDBoxLayout:
                id: talente_section
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 10
                padding: 10   

            # Mächte / Superkräfte Abschnitt
            LeftAlignedLabel:
                id: maechte_header
                text: "Mächte:"
                font_size: '18sp'
                bold: True
                size_hint_y: None
                height: 30
                spacing: 10
                padding: 10

            MDBoxLayout:
                id: maechte_section
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 10
                padding: 10   

            # Ausrüstung Abschnitt
            LeftAlignedLabel:
                text: "Ausrüstung:"
                font_size: '18sp'
                bold: True
                size_hint_y: None
                height: 30
                spacing: 10
                padding: 10 

            MDBoxLayout:
                id: ausruestung_section
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 10
                padding: 10   

            # Waffen Abschnitt
            LeftAlignedLabel:
                text: "Waffen:"
                font_size: '18sp'
                bold: True
                size_hint_y: None
                height: 30
                spacing: 10
                padding: 10 

            MDBoxLayout:
                id: waffen_section
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 10
                padding: 10   

            # Schilde Abschnitt
            LeftAlignedLabel:
                text: "Schild:"
                font_size: '18sp'
                bold: True
                size_hint_y: None
                height: 30
                spacing: 10
                padding: 10 

            MDBoxLayout:
                id: schilde_section
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 10
                padding: 10  

            # Rüstungen Abschnitt
            LeftAlignedLabel:
                text: "Rüstungen:"
                font_size: '18sp'
                bold: True
                size_hint_y: None
                height: 30
                spacing: 10
                padding: 10 

            MDBoxLayout:
                id: ruestungen_section
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 10
                padding: 10   

<WeaponItem@MDBoxLayout>:
    weapon: None
    weapon_text: ''
    button_text: ''
    orientation: 'horizontal'
    size_hint_y: None
    height: 30
    MDLabel:
        text: root.weapon_text
        size_hint_x: 0.8
    MDButton:
        text: root.button_text
        size_hint_x: 0.2
        on_press: root.on_button_press()

<ArmorItem@MDBoxLayout>:
    armor: None
    armor_text: ''
    button_text: ''
    orientation: 'horizontal'
    size_hint_y: None
    height: 30
    MDLabel:
        text: root.armor_text
        size_hint_x: 0.8
    MDButton:
        text: root.button_text
        size_hint_x: 0.2
        on_press: root.on_button_press()

<EquipmentItem@MDBoxLayout>:
    item: None
    item_text: ''
    button_text: ''
    root_widget: None
    orientation: 'horizontal'
    size_hint_y: None
    height: 30

    MDLabel:
        text: root.item_text
        size_hint_x: 0.8

    MDButton:
        text: root.button_text
        size_hint_x: 0.2
        on_press: root.on_button_press()