<MachtDialogContent>:
    orientation: 'vertical'
    spacing: "12dp"
    padding: "12dp"
    size_hint_y: None
    height: "520dp"

    MDTextField:
        id: name_input
        mode: "outlined"
        
        MDTextFieldHintText:
            text: 'Name der Macht'

    MDTextField:
        id: rang_input
        mode: "outlined"
        
        MDTextFieldHintText:
            text: 'Rang'

    MDTextField:
        id: machtpunkte_input
        mode: "outlined"
        input_filter: 'int'
        
        MDTextFieldHintText:
            text: 'Machtpunkte'

    MDTextField:
        id: reichweite_input
        mode: "outlined"
        
        MDTextFieldHintText:
            text: 'Reichweite'

    MDTextField:
        id: dauer_input
        mode: "outlined"
        
        MDTextFieldHintText:
            text: 'Dauer'

    MDTextField:
        id: effekt_input
        mode: "outlined"
        
        MDTextFieldHintText:
            text: 'Effekt'

    MDTextField:
        id: beschreibung_input
        mode: "outlined"
        
        MDTextFieldHintText:
            text: 'Beschreibung'

    MDTextField:
        id: voraussetzungen_input
        mode: "outlined"
        
        MDTextFieldHintText:
            text: 'Voraussetzungen (durch Komma getrennt)'

<DeleteMachtDialogContent>:
    orientation: 'vertical'
    spacing: "12dp"
    padding: "12dp"
    size_hint_y: None
    height: "120dp"

    MDDropDownItem:
        id: macht_dropdown
        pos_hint: {"center_x": .5, "center_y": .5}
        on_release: root.open_menu(self)

        MDDropDownItemText:
            id: selected_macht_text
            text: "Macht auswählen"