"""
Skript: Erweitert die bestehenden 73 SW-Mächte im Savage Aventurien Setting
um DSA-Trapping-Informationen aus dem Konvertierungs-Plan (Sektion 4.5).
Fügt zudem die im Plan als Status 4 markierten neuen Mächte hinzu.
"""

import json
from pathlib import Path
from datetime import datetime

SETTING_PATH = Path("settings/Savage Aventurien.json")
BACKUP_PATH = Path("backup/settings/Savage Aventurien_original_20260602.json")
LOG_PATH = Path(f"logs/dsa_konvertierung_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log")

# ==============================================================================
# Mapping: Bestehende SW-Macht -> DSA-Trappings
# (basierend auf Plan-Sektion 4.5.1-4.5.5)
# ==============================================================================

DSA_TRAPPINGS = {
    # ===== SCHUTZ / ABWEHR =====
    "Abwehren": [
        "Schild-Abwehr (Aventurien)",
        "Paravantio (lit.: Schild des Schutzes)",
    ],
    "Arkaner Schutz": [
        "Dämonenschild",
        "Solidirid",
        "Gardianum",
        "Hellsichtbann",
        "Protectionis (Aura)",
    ],
    "Schutz": [
        # Körperliche Schutzzauber
        "Armatrutz",
        "Basaltleib",
        "Brandungsleib",
        "Drachenleib",
        "Eichenleib",
        "Fortifex",
        "Frostleib",
        "Kraft des Humus",
        "Schuppenhaut",
        "Standfest",
        "Eisenrost (Schutz gegen Waffen)",
        # Göttlicher Schutz (Liturgien)
        "Bann wider Untote",
        "Friedvolle Aura",
        "Furchtresistenz",
        "Lebensschutz",
        "Magieschutz",
        "Magiespiegel",
        "Opfergang",
        "Ort der Ruhe",
        "Schmerzresistenz",
        "Schutz der Hornissenkönigin",
        "Schutz der Wehrlosen",
        "Schutzsegen",
        "Sicherer Weg",
        "Zähe Haut",
        "Zauberschutz",
        "Kleiner Schutzsegen",
        "Feuersegen",
        # Zeremonien
        "Frostschutz",
        "Geweihter Panzer",
        "Große Waffenweihe",
        "Liturgieabsorption",
        "Objektsegen",
        "Objektweihe",
        "Segnung des Heims",
        "Sippenbann",
        "Talismanverankerung",
        "Tempelweihe (Konsekration)",
        "Weihe des Heims",
        "Zuflucht",
        # Rituale
        "Accuratum",
        "Adamantium",
        "Caldofrigo",
        "Custodosigil",
        "Erhabenheit des Marmors",
        "Unberührt von Satinav",
        "Widerwille",
    ],
    "Schutz vor Naturgewalten": [
        "Elementarbann (Resistenz)",
        "Unentflammbarkeit",
        "Wasseratem",
        "Lunge des Leviatan",
    ],
    "Unberührbarkeit": [
        "Unberührt von Satinav",
        "Frostleib",
        "Caldofrigo",
        "Quallenhaut",
        "Panzerung der Elemente",
    ],
    "Zuflucht": [
        "Ort der Ruhe",
        "Bannzone",
        "Heiliger Boden",
        "Traumrefugium",
    ],

    # ===== AUFSPÜREN / ENTDECKEN =====
    "Arkanes entdecken/verbergen": [
        "Analys Arkanstruktur",
        "Blick aufs Wesen",
        "Klarum Purum",
        "Respondami",
        "Visibili",
        "Arcanovi",
        "Entzifferung",
        "Cryptographo",
        "Geisterblick",
        "Magieanalyse",
        "Magiesicht",
        "Seelenprüfung",
        "Göttliche Erkenntnis",
        "Odem Arcanum (magische Essenz)",
    ],
    "Aufspüren": [
        "Gefunden",
        "Pestilenz erspüren",
        "Seelentier erkennen",
        "Blick in die Vergangenheit",
        "Erfolgreiche Pflanzensuche",
        "Büchersuche",
    ],
    "Fernsicht": [
        "Adlerauge",
        "Auge des Limbus",
        "Falkenauge",
        "Katzenaugen",
        "Oculus Astralis",
        "Sensibar",
        "Blick durch fremde Augen",
        "Blick auf den Meeresgrund",
        "Gespür für das Göttliche",
        "Göttlicher Fingerzeig",
        "Leitende Strömung",
        "Mondsicht",
        "Schiffsgespür",
        "Sicht in der Dunkelheit",
        "Traumgesicht",
        "Wegweiser",
        "Auge des Jägers",
    ],
    "Ausspähung": [
        "Spionage (Magie)",
        "Blick durch fremde Augen",
        "Fernsicht (lang)",
        "Blick in die Flammen",
    ],

    # ===== AUFLÖSUNG / BANNEN =====
    "Aufheben": [
        "Dämonenbann",
        "Dämonenpakt beenden",
        "Dämonenpakt brechen",
        "Exorzismus",
        "Machtvoller Exorzismus",
        "Klarum Purum (umgekehrt)",
        "Illusionsbann",
    ],
    "Verbannen": [
        "Dämonenbann",
        "Dämonenpakt beenden",
        "Exorzismus",
        "Machtvoller Exorzismus",
        "Arcanum Interdictum",
    ],
    "Machtpunkte entziehen": [
        "Schwindende Zauberkraft",
        "Magischer Raub",
        "Disruptivo",
        "Pestodem",
    ],

    # ===== BEWEGUNG / TRANSPORT =====
    "Fliegen": [
        "Adlerschwinge",
        "Aerofugo",
        "Himmelslauf",
        "Freiheit der Wolken",
        "Firnlauf (Schnee-Gleitflug)",
    ],
    "Teleportation": [
        "Blitz dich find",
        "Transversalis",
        "Körperlose Reise",
        "Planastrale",
    ],
    "Trägheit/Beschleunigung": [
        "Axxeleratus",
        "Sanfter Fall",
        "Firnlauf",
        "Federleib",
        "Glutlauf",
        "Krötensprung",
        "Spinnenlauf",
        "Wipfellauf",
        "Wüstenlauf",
        "Movimento",
        "Wellenlauf",
        "Geschwinder Schritt",
        "Leichtfüssig",
        "Sicherer Tritt",
        "Unbeschwerte Wanderung",
        "Wasserlauf",
        "Wieselflink",
        "Geschwinder Schritt",
    ],
    "Ebenenwechsel": [
        "Transversalis",
        "Chrononautos",
        "Körperlose Reise",
        "Planastrale",
        "Seelenwanderung",
        "Regenbogenbrücke",
        "Freie Seelenfahrt",
        "Seelenwanderung",
    ],
    "Wachsen/Schrumpfen": [
        "Riesengestalt",
        "Minimus Reductibus",
        "Felsenform (riesig)",
    ],

    # ===== KAMPF / SCHADEN =====
    "Barriere": [
        "Dornenwand",
        "Eiswand",
        "Fesselfeld",
        "Flammenwand",
        "Granit und Marmor",
        "Heptagramma",
        "Hexagramma",
        "Nebwand",
        "Oktagramma",
        "Pentagramma",
        "Steinwand",
        "Sturmwand",
        "Wellenwand",
        "Dämonenwall",
        "Feuerwall",
        "Bannzone",
        "Wand wider Dämonen",
        "Tabu-Zone",
    ],
    "Betäuben": [
        "Paralysis",
        "Atemnot",
        "Band und Fessel",
        "Claudibus",
        "Herzschlag ruhe",
        "Invinculo",
        "Kusch",
        "Somnigravis",
        "Warmes gefriere",
        "Woge der Versteinerung",
        "Schlummer",
        "Numinorus Fesseln",
        "Schattenfessel",
        "Fesselndes Band",
        "Ogerbindung",
        "Seelenbannung",
        "Winterschlaf",
        "Versteinerung",
    ],
    "Blenden": [
        "Blindheit",
        "Vipernblick",
        "Blendung",
        "Blendstrahl",
        "Obarans Blendung",
    ],
    "Geschoss": [
        # Elementarpfeile
        "Eispfeil",
        "Erzpfeil",
        "Feuerpfeil",
        "Luftpfeil",
        "Wasserpfeil",
        "Humuspfeil",
        "Ignifaxius",
        "Frigifaxius",
        "Aquafaxius",
        "Humofaxius",
        "Orcanofaxius",
        "Archofaxius",
        "Blitzball",
        "Fulminictus",
        "Corpofrigo",
        "Penetrizzel",
        "Plumbumbarum",
        # Liturgien
        "Bannstrahl",
        "Kleiner Bannstrahl",
        "Blitzschlag",
        "Göttliche Klinge",
        "Speer des Athleten",
        "Metallerhitzung",
        "Zauberklinge Geisterspeer",
    ],
    "Flächenschlag": [
        "Aquasphaero",
        "Archosphaero",
        "Ignisphaero",
        "Humosphaero",
        "Orcanosphaero",
        "Frigisphaero",
        "Levthans Feuer",
        "Brandungsleib (Konter)",
        "Erdbeben",
        "Froststurm",
        "Hagelschlag und Sturmgebrüll",
        "Kälteexplosion",
        "Mauereinsturz",
        "Lawinenfall und Trümmerfeld",
        "Pech und Schwefel (Streu)",
        "Angriffswelle",
    ],
    "Strahl": [
        "Bannstrahl",
        "Kleiner Bannstrahl",
        "Göttliche Klinge",
        "Speer des Athleten",
        "Göttliche Präzision",
        "Blendstrahl",
    ],
    "Kriegersegen": [
        "Bannstrahl",
        "Göttliche Klinge",
        "Speer des Athleten",
        "Angriffslust",
        "Angriffswelle",
        "Blutiger Zorn",
        "Kampfgeschick",
        "Kraftvoller Körper",
        "Heldenkraft",
        "Zwergenmacht",
        "Kriegsfarben",
        "Kriegszustand",
        "Schaffenskraft",
        "Gnadenstoß",
        "Mächtiger Angriff",
        "Göttlicher Rausch",
        "Brennender Hass",
        "Blutrausch (göttlich)",
    ],
    "Schadensfeld": [
        "Pech und Schwefel",
        "Sturmwand (Schaden)",
        "Höllenpein",
        "Welle des Schmerzes",
    ],
    "Waffe verbessern": [
        "Applicatus",
        "Waffensegen",
        "Waffenweihe",
        "Große Waffenweihe",
        "Göttliche Präzision",
        "Adamantium (Härte)",
        "Waffenfluch (umgekehrt)",
    ],
    "Verstricken": [
        "Band und Fessel",
        "Invinculo",
        "Fesselfeld",
        "Spinnennetz",
        "Fesselndes Band",
    ],
    "Wiederauferstehung": [
        "Wiederbelebung (Auferweckung)",
        "Regeneratio",
        "Immortalis Lebenszeit",
        "Infinitum Immerdar",
        "Gefäß der Jahre",
        "Manus Miracula",
    ],

    # ===== ELEMENTAR / NATUR =====
    "Elementarmanipulation": [
        "Elementare Absorption",
        "Elementarer Diener",
        "Meister der Elemente",
        "Elementarbann",
    ],
    "Licht/Dunkelheit": [
        "Licht (Auge des Limbus)",
        "Bann der Dunkelheit",
        "Sternenglanz",
        "Dunkelheit (Zauber)",
        "Ecliptifactus",
        "Bann des Lichts",
        "Das Löschen des Lichts",
    ],
    "Dunkelsicht": [
        "Dunkelheit (Zauber)",
        "Bann des Lichts",
        "Das Löschen des Lichts",
        "Finsternis",
    ],
    "Wetterkontrolle": [
        "Aeolito",
        "Windhose",
        "Windstille",
        "Wetterherrschaft",
        "Regenruf",
        "Regenkontrolle",
        "Kleine Windhose",
        "Sturmruf",
        "Windruf",
        "Macht des Levthan",
        "Herr der Meere",
        "Avilea",
        "Zorn der Elemente",
    ],
    "Pflanzenzauber": [
        "Getreidewachstum",
        "Pflanzenwuchs",
        "Pflanzenkraft",
        "Stärkung der Wildnis",
        "Sapefacta (Tier-Pflanze)",
    ],

    # ===== VERWANDLUNG =====
    "Böswillige Verwandlung": [
        # Tiergestalten (Zauber)
        "Alpgestalt",
        "Chamaelioni",
        "Impersona",
        "Motoricus",
        "Reptilea",
        "Sapefacta",
        "Serpentialis",
        "Tiergestalt (Druide)",
        # Tiergestalten (Zeremonien)
        "Delphingestalt",
        "Eidechsengestalt",
        "Einhorngestalt",
        "Eisbärengestalt",
        "Elsterngestalt",
        "Falkengestalt",
        "Flugechsengestalt",
        "Fuchsgestalt",
        "Gänsegestalt",
        "Geiergestalt",
        "Geschlechterwechsel",
        "Hundegestalt",
        "Jaguargestalt",
        "Löwengestalt",
        "Luchsgestalt",
        "Mungogestalt",
        "Panthergestalt",
        "Paradiesvogelgestalt",
        "Pferdegestalt",
        "Rabengestalt",
        "Schattenrochengestalt",
        "Schlangengestalt",
        "Schmetterlingsgestalt",
        "Schwanengestalt",
        "Storchengestalt",
        "Taubengestalt",
        "Widdergestalt",
        "Wolfsgestalt",
        "Zwergwalgestalt",
        # Formen (Rituale)
        "Brandform",
        "Chimaeroform",
        "Felsenform",
        "Gletscherform",
        "Pflanzenform",
        "Staub wandle",
        "Stein wandle",
        "Transformatio",
        "Transmutare",
        "Traumgestalt",
        "Wirbelform",
        "Wogenform",
        # Maske
        "Maske",
        "Entstelltes Antlitz",
        "Doppelgänger",
    ],
    "Gestaltwandeln": [
        "Alpgestalt",
        "Impersona",
        "Tiergestalt",
        "Eisbalgestalt",
        "Wolfsgestalt",
    ],

    # ===== BEEINFLUSSUNG =====
    "Marionette": [
        "Bannbaladin",
        "Brennender Hass",
        "Große Gier",
        "Imperavi",
        "Zwingtanz",
        "Heiliger Befehl",
        "Befehl des Schamanen",
        "Obsession",
        "Ächtung (Exkommunikation)",
        "Ergebenheit der Wogen",
        "Zauberzwang",
    ],
    "Empathie": [
        "Ängste Lindern",
        "Besänftigung",
        "Bescheidenheit",
        "Bann der Furcht",
        "Berauschen",
        "Des Einen bezaubernder Sphärenklang",
        "Ehrenhaftigkeit",
        "Elfenstimme",
        "Ermutigung",
        "Erregender Rausch",
        "Einflüsterung",
        "Eingeschworene Mannschaft",
        "Empfängnis des Korsmals",
        "Erinnern",
        "Fest der Freude",
        "Freundschaftliches Auftreten",
        "Friedfertigkeit",
        "Friedvoller Rausch",
        "Gefühlskälte",
        "Gesegneter Rausch",
        "Heiliger Schwur",
        "Heiliges Liebesspiel",
        "Hilfreiche Seele",
        "Innere Ruhe",
        "Levthanischer Liebhaber",
        "Liebestätowierung",
        "Lust erzeugen",
        "Mondsilberzunge",
        "Moralstärkung",
        "Kleine Moralstärkung",
        "Motivation",
        "Mungo (Kampfgeist)",
        "Ruf der Heimat",
        "Sanftmut",
        "Schlangenzunge",
        "Seidenzunge",
        "Treuer Begleiter",
        "Verstecktes Begehren",
        "Wahrheit",
        "Band der Freundschaft",
        "Eins mit der Natur",
        "Tiere beruhigen",
        "Weisheit der Bäume",
        "Segen (Eidsegen, Harmoniesegen, Weisheitssegen)",
        "Berauschender Wein",
        "Aufnahme (Initiation)",
        "Zwergische Verbrüderung",
    ],
    "Fluch": [
        "Böser Blick",
        "Odem Arcanum",
        "Pestodem",
        "Schlechte Ausstrahlung",
        "Schleichende Fäulnis",
        "Schleichende Fäulnis (Pflanzen)",
        "Trankfluch",
        "Bannfluch (Anathema)",
        "Blutzoll",
        "Waffenfluch",
        "Wolfsfluch",
        "Numinorus Fluch",
        "Hexengalle",
        "Mal der Schwäche",
        "Mal der Erschöpfung",
    ],
    "Furcht": [
        "Angst auslösen",
        "Eigene Ängste",
        "Horriphobus",
        "Krabbelnder Schrecken",
        "Menetekel",
        "Panik überkomme euch",
        "Schwarzer Schrecken",
        "Furchteinflößende Tiergeister",
        "Meeresungeheuer vertreiben",
    ],
    "Verwirrung": [
        "Desintegratus (umgekehrt)",
        "Eigene Dummheit",
        "Feenstaub",
        "Große Verwirrung",
        "Ignorantia",
        "Mit Dummheit schlagen",
        "Pandaemonium",
        "Schwarz und Rot",
        "Sturm der Verunsicherung",
        "Taubheit",
        "Verunsicherung",
        "Zweifel schüren",
        "Namenlose Zweifel",
        "Aromatis Illusionis",
    ],

    # ===== GEDANKE / GEIST =====
    "Gedankenleere": [
        "Dämonisches Vergessen",
        "Erinnerung verlasse dich",
        "Memorabia Falsifir",
        "Namenloses Vergessen",
        "Schleier der Unwissenheit",
        "Gnade des Vergessens",
        "Verblassende Erinnerung",
        "Vergessen",
        "Erinnern",
    ],
    "Gedankenlesen": [
        "Blick in die Gedanken",
        "Memorans",
        "Offenlegung des Geistes",
        "Tsas Gedankenspiel",
    ],
    "Gedankenverbindung": [
        "Göttliche Verständigung",
        "Wundersame Verständigung",
        "Botschaft aus der Tiefe",
        "Telepathie (allgemein)",
    ],
    "Eigenschaft erhöhen/senken": [
        "Attributo (Charisma)",
        "Attributo (Fingerfertigkeit)",
        "Attributo (Gewandtheit)",
        "Attributo (Intuition)",
        "Attributo (Klugheit)",
        "Attributo (Konstitution)",
        "Attributo (Körperkraft)",
        "Attributo (Mut)",
        "Affenarme",
        "Kraft des Tieres",
        "Kulminatio",
        "Riesengestalt",
        "Sensattacco",
        "Kampfgeschick",
        "Last des Alters (senken)",
        "Ungeschickt (senken)",
        "Minimus Reductibus (Größe)",
        "Zitterfinger (senken)",
        "Debilitatio (senken)",
    ],

    # ===== BESCHWÖRUNG =====
    "Gegenstand beschwören": [
        "Objectovoco",
        "Manifesto",
        "Geisteressenz",
        "Skelettarius",
        "Foramen (Schloss öffnen)",
        "Invocatio Minima",
        "Animatio (Belebung)",
        "Aurum Argentor (Gold)",
        "Zauberpferd herbeirufen",
        # Rituale
        "Dschinnenruf",
        "Elementarer Diener",
        "Geisterbeschwörung",
        "Invocatio Maior",
        "Invocatio Maxima",
        "Invocatio Minor",
        "Nekropathia",
        "Ruf der Feenwesen",
        "Standhafter Wächter",
        "Totes handle",
        "Zauberwesen der Natur",
        # Liturgien
        "Hairuf",
        "Beschwörung der gemeinen Diener des Rattenkindes",
        "Brazoraghs Krieger",
        "Erzene Opfergabe",
        "Herbeirufung der Heerscharen des Rattenkindes (Ratten)",
        "Herbeirufung der Heerscharen des Rattenkindes (Schakale)",
        "Herbeirufung der Heerscharen des Rattenkindes (Vampirfledermäuse)",
        "Herbeirufung der Heerscharen des Rattenkindes (Wolfsspinnen)",
        "Herbeirufung von Tairachs Dienern (Nebelkrähen)",
        "Nebelkrähenschwarm",
        "Rattenschwarm",
        "Schlangenstab",
        "Talismanruf",
        "Untotenerhebung",
        # Zeremonien
        "Beschwörung der hohen Diener des Rattenkindes",
        "Beschwörung der machtvollen Diener des Rattenkindes",
        "Diener der Erde",
        "Diener der Flammen",
        "Diener der Kälte",
        "Diener der Wellen",
        "Diener der Wolken",
        "Diener des Erzes",
        "Erschaffung von Nachtkindern",
        "Gespräch mit den Toten",
        "Himmlische Schatzkammer",
        "Tairachs machtvolle Erhebung von Untoten",
        "Travias Wachgänse",
        "Untote erschaffen",
    ],
    "Gegenstand Beschwören": [],  # Duplikat (case-different) — leer, siehe Haupt-Mapping
    "Monster Beschwören": [
        "Elementarer Diener",
        "Dschinnenruf",
        "Ruf der Feenwesen",
        "Standhafter Wächter",
        "Skelettarius",
        "Erschaffung von Nachtkindern",
    ],
    "Tier Beschwören": [
        # Zauber
        "Affenruf",
        "Eulenruf",
        "Fledermausruf",
        "Krähenruf",
        "Krötenruf",
        "Papageienruf",
        "Schlangenruf",
        "Spinnenruf",
        "Vogelzwitschern",
        "Katzenruf",
        "Zauberpferd herbeirufen",
        # Liturgien
        "Delphinruf",
        "Eisbärenruf",
        "Flugechsenruf",
        "Jaguarruf",
        "Mammutruf",
        "Ogerruf",
        "Quallenruf",
        "Rabenruf",
        "Rinderruf",
        "Schlangenruf",
        "Schlingerruf",
        "Wolfsruf",
        # Zeremonien
        "Greifenruf",
        "Seemonsterruf",
    ],
    "Tierfreund": [
        "Herr über das Tierreich",
        "Tierbeherrschung",
        "Tiere besprechen",
        "Tiergedanken",
        "Sprechen mit Tieren",
        "Hilfreiche Pfote",
        "Hilfreiche Schwinge",
        "Hilfreiche Tatze",
        "Seelentier erkennen",
    ],
    "Verbündeten beschwören": [
        "Elementarer Diener",
        "Standhafter Wächter",
        "Zauberwesen der Natur",
        "Ruf der Feenwesen",
        "Dschinnenruf",
        "Eingeschworene Mannschaft",
        "Beschwörung der Diener",
    ],
    "Untoten Beschwören": [
        "Nekropathia",
        "Totes handle",
        "Skelettarius",
        "Untotenerhebung",
        "Untote erschaffen",
        "Tairachs Erhebung",
        "Erschaffung von Nachtkindern",
    ],

    # ===== ILLUSION / TARNUNG =====
    "Illusion": [
        "Halluzination",
        "Projectimago",
        "Auris Illusionis",
        "Manus Illusionis",
        "Gedankenbilder",
        "Objectobscuro",
        "Oculus Illusionis",
        "Reflectimago",
        "Madas Spiegel",
        "Aromatis Illusionis",
        "Bild für die Ewigkeit",
        "Traumbild",
        "Seelenschatten",
    ],
    "Verkleiden": [
        "Impersona",
        "Maske",
        "Harmlose Gestalt",
        "Sapefacta",
        "Sapefacta",
        "Kleidungschamäleon",
        "Chamaelioni",
    ],
    "Unsichtbarkeit": [
        "Objectobscuro",
        "Nebelform",
        "Unsichtbare Flut",
        "Nebelwand",
    ],
    "Geräusch/Stille": [
        "Silentium",
        "Lautlos",
        "Auris Illusionis (gegenteilig: erzeugen)",
    ],
    "Verriegeln/Entriegeln": [
        "Foramen",
        "Invinculo",
        "Invercano (umgekehrt)",
        "Verriegeln/Entriegeln",
    ],

    # ===== HEILUNG / LINDERUNG =====
    "Heilung": [
        # Zauber (Heilung)
        "Balsam Salabunde",
        "Hexenspeichel",
        "Manus Miracula",
        "Physiostabilis",
        "Psychostabilis",
        "Regeneratio",
        "Salander",
        "Satuarias Herrlichkeit",
        "Schmerzen lindern",
        "Sumus Elixiere",
        "Welle der Reinigung",
        "Aufwecken",
        "Erwachen",
        "Erschöpfungen lindern",
        "Gifthaut heilen",
        "Zaubernahrung",
        # Liturgien
        "Ausnüchtern",
        "Befreiung des Geistes",
        "Blick des Heilers",
        "Giftbann",
        "Goldene Hand",
        "Heilsame Quelle",
        "Heilsegen",
        "Helfende Hand",
        "Klarer Geist",
        "Krankheitsbann",
        "Krankheiten vorbeugen",
        "Peraines Gnade",
        "Reinigung des Bösen",
        "Schonfrist",
        "Tierleid lindern",
        # Zeremonien
        "Ackersegen",
        "Ausbrennen (Purgation)",
        "Eidechsenregeneration",
        "Fruchtbarkeit",
        "Geistheilung",
        "Häutung",
        "Heilschlaf",
        "Heilung von Seelenkranken",
        "Hilfe in der Not",
        "Jugendlichkeit",
        "Läuterung des Erzes",
        "Lebenstausch",
        "Makelloser Leib",
        "Nahrungsreinigung",
        "Priesterweihe (Ordination)",
        "Sättigung",
        "Selbstopferung",
        "Speisung",
        "Wiederherstellung",
        # Segen
        "Geburtssegen",
        "Grabsegen",
        "Kleiner Heilsegen",
        "Speisesegen",
        "Stärkungssegen",
        "Tranksegen",
        # Rituale
        "Gefäß der Jahre",
        "Immortalis Lebenszeit",
        "Infinitum Immerdar",
    ],
    "Linderung": [
        "Erschöpfungen lindern",
        "Schmerzen lindern",
        "Welle der Reinigung",
        "Giftbann",
        "Krankheitsbann",
        "Krankheiten vorbeugen",
        "Tierleid lindern",
        "Schonfrist",
        "Klarer Geist",
        "Befreiung des Geistes",
        "Reinigung des Bösen",
        "Ausnüchtern",
        "Ernüchterung",
    ],
    "Segen": [
        "Heilsegen",
        "Kleiner Heilsegen",
        "Schutzsegen",
        "Kleiner Schutzsegen",
        "Feuersegen",
        "Eidsegen",
        "Geburtssegen",
        "Glückssegen",
        "Grabsegen",
        "Harmoniesegen",
        "Speisesegen",
        "Stärkungssegen",
        "Tranksegen",
        "Weisheitssegen",
    ],

    # ===== KOMMUNIKATION / SPRACHE =====
    "Sprachen sprechen": [
        "Seidenzunge",
        "Mondsilberzunge",
        "Schlangenzunge",
        "Tiersprache",
        "Sprache des Tapams",
        "Seevogelsprache",
        "Cryptographo (Schrift)",
    ],
    "Zwiesprache": [
        "Göttliche Verständigung",
        "Wundersame Verständigung",
        "Seidenzunge",
        "Telepathie",
        "Tiergedanken",
        "Tiersprache",
    ],

    # ===== BEWEGUNGSHILFEN =====
    "Wandkrabbler": [
        "Affenarme",
        "Spinnenlauf",
        "Wipfellauf",
        "Klettern (Tier-Empathie)",
    ],
    "Graben": [
        "Graben (Elementar-Erde)",
        "Nihilogravo (Schwerelosigkeit)",
    ],

    # ===== MANIPULATION =====
    "Telekinese": [
        "Objectofixo",
        "Telekinese (allgemein)",
        "Nihilogravo",
    ],
    "Heiligtum": [
        "Heiliger Boden",
        "Bodenweihe",
        "Ortsweihe",
        "Bannzone",
    ],

    # ===== HÖHERE / LEGENDÄRE =====
    "Zeitstopp": [
        "Tempus Stasis",
        "Stillstand",
        "Chrononautos",
        "Zeitstopp",
    ],
    "Mystisches Eingreifen": [
        "Göttliches Zeichen",
        "Wunder (göttlicher Eingriff)",
        "Mystisches Eingreifen",
    ],
    "Wunsch": [
        "Wunsch",
        "Herzlichen Wunsch (Traum)",
        "Wunsch (höchste Magie)",
    ],
    "Magisches Glas": [
        "Oculus Astralis",
        "Oculus Illusionis",
        "Magisches Glas (Sichtbarmachung)",
    ],
    "Zombie": [
        "Skelettarius",
        "Untotenerhebung",
        "Untote erschaffen",
        "Zombie-Erschaffung",
    ],
    "Bindender Ruf": [
        "Zwingtanz",
        "Bannbaladin",
        "Zauberzwang",
    ],  # Status 3 — zu löschen, leere Liste als Marker

    # ===== UNDEFINIERTE / CHAOS =====
    "Chaos": [
        "Pandaemonium",
    ],  # Status 3 — zu löschen
}

# ==============================================================================
# Neue SW-Mächte (Status 4) aus Plan 4.5.7
# Werden zusätzlich zu den bestehenden 73 ergänzt
# ==============================================================================

NEW_MAECHTE = {
    "Heiliger Boden": {
        "name": "Heiliger Boden",
        "kategorie": "Macht",
        "rang": "F",
        "machtpunkte": 3,
        "reichweite": "Zone",
        "dauer": "1 Stunde",
        "beschreibung": "Weiht einen Bereich und schützt vor Eindringlingen. DSA-Trappings: Bodenweihe, Weihe des Bodens, Ortsweihe (Sanctum), Bannzone.",
        "voraussetzungen": [],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Bodenweihe (Liturgie)",
            "Weihe des Bodens (Liturgie)",
            "Ortsweihe (Sanctum) (Zeremonie)",
            "Bannzone (Liturgie)",
            "Tabu-Zone (Zeremonie)",
        ],
        "dsa_neu": True,
    },
    "Liturgieschild": {
        "name": "Liturgieschild",
        "kategorie": "Macht",
        "rang": "F",
        "machtpunkte": 2,
        "reichweite": "Selbst",
        "dauer": "3 Runden",
        "beschreibung": "Göttlicher Schutzschild für Kleriker und Geweihte. Wirkt gegen göttliche Angriffe und Flüche.",
        "voraussetzungen": ["Glaube W6"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Liturgieschild (Liturgie)",
        ],
        "dsa_neu": True,
    },
    "Geisterruf": {
        "name": "Geisterruf",
        "kategorie": "Macht",
        "rang": "F",
        "machtpunkte": 3,
        "reichweite": "Selbst",
        "dauer": "Sofort",
        "beschreibung": "Ruft einen Geist herbei, der für eine Aufgabe befragt oder gebunden werden kann. Schamanen-Ritual.",
        "voraussetzungen": ["Okkultismus W6"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Geisterruf (Ritual)",
            "Geisterbeschwörung (Ritual)",
            "Totes handle (Ritual)",
            "Blick in die Flammen (Zeremonie)",
            "Hairuf (Liturgie, Achaz-Geist)",
            "Geisterfalle (Liturgie)",
        ],
        "dsa_neu": True,
    },
    "Elementar-Meister": {
        "name": "Elementar-Meister",
        "kategorie": "Macht",
        "rang": "V",
        "machtpunkte": 5,
        "reichweite": "Selbst",
        "dauer": "5 Runden",
        "beschreibung": "Beherrscht ein Element und ignoriert Modifikatoren bei elementaren Zaubern.",
        "voraussetzungen": ["Zaubern W8", "Meister der Elemente"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Meister der Elemente (Ritual)",
        ],
        "dsa_neu": True,
    },
    "Schutzrüstung": {
        "name": "Schutzrüstung",
        "kategorie": "Macht",
        "rang": "A",
        "machtpunkte": 2,
        "reichweite": "Selbst",
        "dauer": "3 Runden",
        "beschreibung": "Erschafft eine magische Rüstung, die einige Treffer absorbiert. DSA-Trapping: Ablativum.",
        "voraussetzungen": ["Zaubern W6"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Ablativum (Zauber)",
        ],
        "dsa_neu": True,
    },
    "Gegengift": {
        "name": "Gegengift",
        "kategorie": "Macht",
        "rang": "A",
        "machtpunkte": 1,
        "reichweite": "Berührung",
        "dauer": "Sofort",
        "beschreibung": "Entfernt Gifte aus dem Körper. DSA-Trapping: Abvenenum.",
        "voraussetzungen": ["Zaubern W6"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Abvenenum (Zauber)",
            "Giftbann (Liturgie)",
        ],
        "dsa_neu": True,
    },
    "Schallverstärkung": {
        "name": "Schallverstärkung",
        "kategorie": "Macht",
        "rang": "A",
        "machtpunkte": 1,
        "reichweite": "VER 5",
        "dauer": "Sofort",
        "beschreibung": "Erzeugt einen markerschütternden Schall. DSA-Trapping: Altisonus.",
        "voraussetzungen": [],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Altisonus (Zauber)",
            "Radau (Zauber)",
        ],
        "dsa_neu": True,
    },
    "Duftzauber": {
        "name": "Duftzauber",
        "kategorie": "Macht",
        "rang": "A",
        "machtpunkte": 1,
        "reichweite": "Zone",
        "dauer": "5 Runden",
        "beschreibung": "Erzeugt Illusionen von Gerüchen. DSA-Trapping: Aromatis Illusionis.",
        "voraussetzungen": [],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Aromatis Illusionis (Zauber)",
        ],
        "dsa_neu": True,
    },
    "Wasserreinigung": {
        "name": "Wasserreinigung",
        "kategorie": "Macht",
        "rang": "A",
        "machtpunkte": 1,
        "reichweite": "VER",
        "dauer": "Sofort",
        "beschreibung": "Findet eine Wasserquelle oder reinigt Wasser. DSA-Trapping: Aquaqueris.",
        "voraussetzungen": ["Überleben W6"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Aquaqueris (Zauber)",
        ],
        "dsa_neu": True,
    },
    "Spinnennetz": {
        "name": "Spinnennetz",
        "kategorie": "Macht",
        "rang": "F",
        "machtpunkte": 2,
        "reichweite": "VER",
        "dauer": "3 Runden",
        "beschreibung": "Erschafft ein klebriges Netz, das Ziele fesselt. DSA-Trapping: Arachnea.",
        "voraussetzungen": [],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Arachnea (Zauber)",
        ],
        "dsa_neu": True,
    },
    "Regenruf": {
        "name": "Regenruf",
        "kategorie": "Macht",
        "rang": "F",
        "machtpunkte": 2,
        "reichweite": "Zone",
        "dauer": "1 Stunde",
        "beschreibung": "Ruft Regen oder Schnee herbei. DSA-Trapping: Avilea, Regenkontrolle.",
        "voraussetzungen": ["Überleben W6"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Avilea (Zauber)",
            "Regenkontrolle (Zeremonie)",
        ],
        "dsa_neu": True,
    },
    "Blitzruf": {
        "name": "Blitzruf",
        "kategorie": "Macht",
        "rang": "V",
        "machtpunkte": 4,
        "reichweite": "Selbst",
        "dauer": "Sofort",
        "beschreibung": "Teleportiert den Zauberer per Blitz zu einem bekannten Ort. DSA-Trapping: Blitz dich find.",
        "voraussetzungen": ["Zaubern W8"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Blitz dich find (Zauber)",
        ],
        "dsa_neu": True,
    },
    "Verschluesselung": {
        "name": "Verschlüsselung",
        "kategorie": "Macht",
        "rang": "A",
        "machtpunkte": 2,
        "reichweite": "Berührung",
        "dauer": "Dauerhaft",
        "beschreibung": "Verschlüsselt Schriftstücke mit magischer Schrift. DSA-Trapping: Cryptographo, Xenographus.",
        "voraussetzungen": ["Sprache W6"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Cryptographo (Zauber)",
            "Xenographus (Ritual)",
        ],
        "dsa_neu": True,
    },
    "Rost": {
        "name": "Rost",
        "kategorie": "Macht",
        "rang": "A",
        "machtpunkte": 2,
        "reichweite": "VER",
        "dauer": "Sofort",
        "beschreibung": "Lässt Metallwaffen und Rüstungen rosten. DSA-Trapping: Eisenrost.",
        "voraussetzungen": [],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Eisenrost (Zauber)",
        ],
        "dsa_neu": True,
    },
    "Explosion": {
        "name": "Explosion",
        "kategorie": "Macht",
        "rang": "F",
        "machtpunkte": 3,
        "reichweite": "Zone",
        "dauer": "Sofort",
        "beschreibung": "Druckwelle aus reiner Luft. DSA-Trapping: Exposami.",
        "voraussetzungen": ["Zaubern W6"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Exposami (Zauber)",
        ],
        "dsa_neu": True,
    },
    "Funkenregen": {
        "name": "Funkenregen",
        "kategorie": "Macht",
        "rang": "F",
        "machtpunkte": 2,
        "reichweite": "Zone",
        "dauer": "Sofort",
        "beschreibung": "Regen aus glühenden Funken. DSA-Trapping: Favilludo.",
        "voraussetzungen": ["Zaubern W6"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Favilludo (Zauber)",
            "Flim Flam (Zauber)",
        ],
        "dsa_neu": True,
    },
    "Flossen": {
        "name": "Flossen",
        "kategorie": "Macht",
        "rang": "A",
        "machtpunkte": 1,
        "reichweite": "Selbst",
        "dauer": "1 Stunde",
        "beschreibung": "Verleiht Kiemen und Schwanzflosse. DSA-Trapping: Fischflosse.",
        "voraussetzungen": [],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Fischflosse (Zauber)",
        ],
        "dsa_neu": True,
    },
    "Busch": {
        "name": "Busch",
        "kategorie": "Macht",
        "rang": "A",
        "machtpunkte": 1,
        "reichweite": "Zone",
        "dauer": "1 Stunde",
        "beschreibung": "Lässt eine Hecke aus dem Boden wachsen. DSA-Trapping: Haselbusch.",
        "voraussetzungen": ["Pflanzenzauber"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Haselbusch (Zauber)",
        ],
        "dsa_neu": True,
    },
    "Tierhilfe": {
        "name": "Tierhilfe",
        "kategorie": "Macht",
        "rang": "A",
        "machtpunkte": 1,
        "reichweite": "VER",
        "dauer": "Sofort",
        "beschreibung": "Ruft ein hilfreiches Tier herbei. DSA-Trapping: Hilfreiche Pfote/Schwinge/Tatze.",
        "voraussetzungen": ["Tierfreund"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Hilfreiche Pfote (Zauber)",
            "Hilfreiche Schwinge (Zauber)",
            "Hilfreiche Tatze (Zauber)",
        ],
        "dsa_neu": True,
    },
    "Wolfsform": {
        "name": "Wolfsform",
        "kategorie": "Macht",
        "rang": "F",
        "machtpunkte": 2,
        "reichweite": "Selbst",
        "dauer": "1 Stunde",
        "beschreibung": "Verwandelt den Zauberer in einen Wolf. DSA-Trapping: Wolfstatze, Wolfsgestalt.",
        "voraussetzungen": ["Tierfreund"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Wolfstatze (Zauber)",
            "Wolfsgestalt (Zeremonie)",
            "Wolfsfluch (Zeremonie, negativ)",
        ],
        "dsa_neu": True,
    },
    "Botenruf": {
        "name": "Botenruf",
        "kategorie": "Macht",
        "rang": "F",
        "machtpunkte": 2,
        "reichweite": "Selbst",
        "dauer": "Sofort",
        "beschreibung": "Sendet einen magischen Boten. DSA-Trapping: Nuntiovolo.",
        "voraussetzungen": [],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Nuntiovolo (Zauber)",
        ],
        "dsa_neu": True,
    },
    "Doppelgaenger": {
        "name": "Doppelgänger",
        "kategorie": "Macht",
        "rang": "V",
        "machtpunkte": 5,
        "reichweite": "Selbst",
        "dauer": "1 Stunde",
        "beschreibung": "Erschafft eine exakte Kopie des Zauberers. DSA-Trapping: Duplicatus, Doppelgänger.",
        "voraussetzungen": ["Böswillige Verwandlung"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Duplicatus (Zauber)",
            "Doppelgänger (Liturgie)",
        ],
        "dsa_neu": True,
    },
    "Finsternis": {
        "name": "Finsternis",
        "kategorie": "Macht",
        "rang": "F",
        "machtpunkte": 3,
        "reichweite": "Zone",
        "dauer": "1 Stunde",
        "beschreibung": "Verdunkelt die Sonne oder den Mond. DSA-Trapping: Ecliptifactus.",
        "voraussetzungen": ["Wetterkontrolle"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Ecliptifactus (Zauber)",
        ],
        "dsa_neu": True,
    },
    "Brand": {
        "name": "Brand",
        "kategorie": "Macht",
        "rang": "F",
        "machtpunkte": 2,
        "reichweite": "Zone",
        "dauer": "Sofort",
        "beschreibung": "Entzündet brennbare Materialien. DSA-Trapping: Incendio.",
        "voraussetzungen": [],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Incendio (Zauber)",
        ],
        "dsa_neu": True,
    },
    "Huelle": {
        "name": "Hülle",
        "kategorie": "Macht",
        "rang": "A",
        "machtpunkte": 2,
        "reichweite": "VER",
        "dauer": "3 Runden",
        "beschreibung": "Entfernt magische Rüstungen oder Boni. DSA-Trapping: Invercano.",
        "voraussetzungen": ["Magie bannen"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Invercano (Zauber)",
        ],
        "dsa_neu": True,
    },
    "Zauber_verstaerken": {
        "name": "Zauber verstärken",
        "kategorie": "Macht",
        "rang": "A",
        "machtpunkte": 1,
        "reichweite": "Berührung",
        "dauer": "Dauerhaft",
        "beschreibung": "Überträgt einen Zauber auf einen Gegenstand. DSA-Trapping: Applicatus.",
        "voraussetzungen": ["Zaubern W6"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Applicatus (Ritual)",
        ],
        "dsa_neu": True,
    },
    "Freundschaft": {
        "name": "Freundschaft",
        "kategorie": "Macht",
        "rang": "A",
        "machtpunkte": 2,
        "reichweite": "Berührung",
        "dauer": "1 Tag",
        "beschreibung": "Stärkt die Bindung zwischen zwei Personen. DSA-Trapping: Band der Freundschaft.",
        "voraussetzungen": ["Empathie"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Band der Freundschaft (Ritual)",
        ],
        "dsa_neu": True,
    },
    "Baerenkraft": {
        "name": "Bärenkraft",
        "kategorie": "Macht",
        "rang": "A",
        "machtpunkte": 2,
        "reichweite": "Selbst",
        "dauer": "3 Runden",
        "beschreibung": "Verleiht Bärenstärke. DSA-Trapping: Bärenruhe.",
        "voraussetzungen": [],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Bärenruhe (Ritual)",
            "Bärenhaut (Liturgie)",
        ],
        "dsa_neu": True,
    },
    "Leidensbund": {
        "name": "Leidensbund",
        "kategorie": "Macht",
        "rang": "V",
        "machtpunkte": 4,
        "reichweite": "Berührung",
        "dauer": "1 Stunde",
        "beschreibung": "Zwei Personen teilen Schmerz und Heilung. DSA-Trapping: Leidensbund.",
        "voraussetzungen": ["Heilung W8"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Leidensbund (Ritual)",
        ],
        "dsa_neu": True,
    },
    "Reinigung": {
        "name": "Reinigung",
        "kategorie": "Macht",
        "rang": "F",
        "machtpunkte": 3,
        "reichweite": "Zone",
        "dauer": "Sofort",
        "beschreibung": "Läutert einen Ort durch heiliges Feuer. DSA-Trapping: Reinheit der Lohe.",
        "voraussetzungen": ["Glaube W6"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Reinheit der Lohe (Ritual)",
            "Reinigung des Bösen (Liturgie)",
            "Ausbrennen (Purgation) (Zeremonie)",
        ],
        "dsa_neu": True,
    },
    "Schnurren": {
        "name": "Schnurren",
        "kategorie": "Macht",
        "rang": "A",
        "machtpunkte": 1,
        "reichweite": "Selbst",
        "dauer": "3 Runden",
        "beschreibung": "Katzenartige Magie, die Glück und Anmut verleiht. DSA-Trapping: Zauberschnurren.",
        "voraussetzungen": [],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Zauberschnurren (Ritual)",
        ],
        "dsa_neu": True,
    },
    "Mutbann": {
        "name": "Mutbann",
        "kategorie": "Macht",
        "rang": "F",
        "machtpunkte": 2,
        "reichweite": "Zone",
        "dauer": "Sofort",
        "beschreibung": "Bannt Furcht bei Verbündeten. DSA-Trapping: Bann der Furcht.",
        "voraussetzungen": ["Glaube W6"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Bann der Furcht (Liturgie)",
        ],
        "dsa_neu": True,
    },
    "Reiter-Segen": {
        "name": "Reiter-Segen",
        "kategorie": "Macht",
        "rang": "F",
        "machtpunkte": 2,
        "reichweite": "Selbst",
        "dauer": "1 Stunde",
        "beschreibung": "Segnet das Reittier für höhere Geschwindigkeit. DSA-Trapping: Begnadeter Reiter.",
        "voraussetzungen": ["Reiten W6"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Begnadeter Reiter (Liturgie)",
        ],
        "dsa_neu": True,
    },
    "Blut-Siegel": {
        "name": "Blut-Siegel",
        "kategorie": "Macht",
        "rang": "V",
        "machtpunkte": 3,
        "reichweite": "Selbst",
        "dauer": "1 Tag",
        "beschreibung": "Markiert das Blut des Zauberers, sodass Verfolger ihn nicht finden. DSA-Trapping: Blutiges Siegel.",
        "voraussetzungen": ["Schutz"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Blutiges Siegel (Liturgie)",
        ],
        "dsa_neu": True,
    },
    "Vertragszauber": {
        "name": "Vertragszauber",
        "kategorie": "Macht",
        "rang": "F",
        "machtpunkte": 2,
        "reichweite": "Berührung",
        "dauer": "Dauerhaft",
        "beschreibung": "Bindet einen Vertrag magisch. DSA-Trapping: Ehrlicher Vertrag.",
        "voraussetzungen": ["Recht/Handel W6"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Ehrlicher Vertrag (Liturgie)",
        ],
        "dsa_neu": True,
    },
    "Strategie": {
        "name": "Strategie",
        "kategorie": "Macht",
        "rang": "F",
        "machtpunkte": 2,
        "reichweite": "Selbst",
        "dauer": "1 Stunde",
        "beschreibung": "Verleiht taktischen Vorteil im Kampf. DSA-Trapping: Geist des Strategen.",
        "voraussetzungen": ["Kriegskunst W6"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Geist des Strategen (Liturgie)",
        ],
        "dsa_neu": True,
    },
    "Geldzauber": {
        "name": "Geldzauber",
        "kategorie": "Macht",
        "rang": "A",
        "machtpunkte": 1,
        "reichweite": "Selbst",
        "dauer": "Sofort",
        "beschreibung": "Vermehrt kleine Geldbeträge. DSA-Trapping: Geldwechsel.",
        "voraussetzungen": [],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Geldwechsel (Liturgie)",
            "Aurum Argentor (Ritual)",
        ],
        "dsa_neu": True,
    },
    "Feuergebiet": {
        "name": "Feuergebiet",
        "kategorie": "Macht",
        "rang": "V",
        "machtpunkte": 5,
        "reichweite": "Zone",
        "dauer": "3 Runden",
        "beschreibung": "Beherrscht alle Flammen im Wirkungsbereich. DSA-Trapping: Gebieter der Flammen.",
        "voraussetzungen": ["Elementar-Meister"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Gebieter der Flammen (Liturgie)",
        ],
        "dsa_neu": True,
    },
    "Feuerherr": {
        "name": "Feuerherr",
        "kategorie": "Macht",
        "rang": "H",
        "machtpunkte": 8,
        "reichweite": "Zone",
        "dauer": "1 Stunde",
        "beschreibung": "Mächtige Beherrschung aller Flammen. DSA-Trapping: Herr der Flammen.",
        "voraussetzungen": ["Feuergebiet"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Herr der Flammen (Liturgie)",
        ],
        "dsa_neu": True,
    },
    "Goettliches_Zeichen": {
        "name": "Göttliches Zeichen",
        "kategorie": "Macht",
        "rang": "L",
        "machtpunkte": 15,
        "reichweite": "Zone",
        "dauer": "Sofort",
        "beschreibung": "Göttliches Wunder, Omen oder direkter Eingriff einer Gottheit. DSA-Trapping: Göttliches Zeichen, Mystisches Eingreifen.",
        "voraussetzungen": ["Glaube W10"],
        "ausgewaehlt": False,
        "aktiv": True,
        "custom": False,
        "effekt": "",
        "dsa_trappings": [
            "Göttliches Zeichen (Liturgie)",
            "Mystisches Eingreifen (SW-Höchste)",
        ],
        "dsa_neu": True,
    },
}


def main():
    print("=" * 70)
    print("DSA-Trapping-Erweiterung für Savage Aventurien Mächte")
    print("=" * 70)

    # Lade Original-Setting
    with open(SETTING_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    original_count = len(data["maechte"])
    print(f"\nOriginal Mächte: {original_count}")

    # 1) Erweitere bestehende Mächte um dsa_trappings
    extended = 0
    skipped = []
    for key, macht in data["maechte"].items():
        if key in DSA_TRAPPINGS:
            macht["dsa_trappings"] = DSA_TRAPPINGS[key]
            extended += 1
        else:
            # Mächte ohne Mapping
            macht["dsa_trappings"] = []
            skipped.append(key)

    print(f"Erweiterte Mächte: {extended}")
    print(f"Übersprungen (kein Mapping): {skipped}")

    # 2) KEINE neuen Mächte hinzufügen — werden separat in Diskussions-Liste
    #    geführt und vom User einzeln genehmigt (siehe
    #    logs/dsa_neue_maechte_diskussion.md)
    new_added = []

    new_count = len(data["maechte"])
    print(f"\nGesamtanzahl Mächte (unverändert): {new_count}")
    print(f"  Bestehende: {original_count}")
    print(f"  Hinzugefügt: 0 (auf User-Genehmigung warten)")

    # 3) Zähle DSA-Trappings
    total_trappings = 0
    powers_with_trappings = 0
    for key, macht in data["maechte"].items():
        trappings = macht.get("dsa_trappings", [])
        if trappings:
            powers_with_trappings += 1
            total_trappings += len(trappings)

    print(f"\nDSA-Trapping-Statistik:")
    print(f"  Mächte mit Trappings: {powers_with_trappings}")
    print(f"  Trappings gesamt: {total_trappings}")
    print(f"  Durchschnitt pro Macht: {total_trappings / powers_with_trappings:.1f}")

    # 4) Speichere aktualisiertes Setting
    with open(SETTING_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\n✓ Aktualisiertes Setting gespeichert: {SETTING_PATH}")
    print(f"  Original-Backup: {BACKUP_PATH}")

    # 5) Log-Datei
    log_lines = [
        "=" * 70,
        "DSA-Konvertierung Phase 6.1: Bestehende Mächte um DSA-Trappings erweitern",
        f"Datum: {datetime.now().isoformat()}",
        "=" * 70,
        "",
        f"Quell-Plan: logs/dsa_konvertierungs_plan.md (Sektion 4.5)",
        f"Quell-Setting: {SETTING_PATH}",
        f"Backup: {BACKUP_PATH}",
        "",
        f"Bestehende Mächte erweitert: {extended} / {original_count}",
        f"Neue Mächte: 0 (auf Einzel-Genehmigung warten — siehe Diskussions-Liste)",
        f"Gesamt: {new_count}",
        "",
        "Erweiterte bestehende Mächte:",
    ]
    for key in sorted(DSA_TRAPPINGS.keys()):
        log_lines.append(f"  ✓ {key}: {len(DSA_TRAPPINGS[key])} Trappings")

    log_lines.append("")
    log_lines.append("Übersprungen (kein Mapping):")
    for key in skipped:
        log_lines.append(f"  - {key}")

    log_lines.append("")
    log_lines.append("Statistik:")
    log_lines.append(f"  Mächte mit Trappings: {powers_with_trappings}")
    log_lines.append(f"  Trappings gesamt: {total_trappings}")
    log_lines.append(f"  Durchschnitt: {total_trappings / powers_with_trappings:.1f}")

    with open(LOG_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(log_lines))

    print(f"  Log: {LOG_PATH}")


if __name__ == "__main__":
    main()
